import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

import { universitiesData as existing } from '../src/data/universitiesData.js';

const existingIds = new Set(existing.map(u => u.id));

const newUniversities = [
  {
    id: 'uni-8',
    name: 'Universidad Nacional Agraria La Molina',
    acronym: 'UNALM',
    type: 'Universidad Pública',
    typeCategory: 'publica',
    region: 'Lima',
    regionsAvailable: ['Lima'],
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'Líder en ciencias agrarias, biotecnología, industrias alimentarias, gestión ambiental y recursos forestales en el Perú.',
    carreras: ['Agronomía', 'Industrias Alimentarias', 'Ingeniería Ambiental', 'Biología', 'Economía Agraria'],
    becas: ['Comedor Universitario Gratuito', 'Beca Pronabec Permanencia', 'Intercambios en Alemania y Francia'],
    admision: 'Examen de Admisión Ordinario 2026.',
    website: 'https://www.lamolina.edu.pe/',
    featured: true
  },
  {
    id: 'uni-9',
    name: 'Universidad Peruana Cayetano Heredia',
    acronym: 'UPCH',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Lima',
    regionsAvailable: ['Lima'],
    logo: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'La institución médica y científica número 1 del Perú en producción de investigación biomédica y formación en salud.',
    carreras: ['Medicina Humana', 'Estomatología', 'Enfermería', 'Biología Molecular', 'Farmacia y Bioquímica'],
    becas: ['Beca Talento BCP', 'Beca 18 Pronabec', 'Beca Estímulo Académico Cayetano'],
    admision: 'Factor Excelencia y Examen General 2026.',
    website: 'https://www.cayetano.edu.pe/',
    featured: true
  },
  {
    id: 'uni-10',
    name: 'Universidad de Lima',
    acronym: 'ULIMA',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Lima',
    regionsAvailable: ['Lima'],
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'Reconocida por su excelencia en comunicación, ingeniería industrial, arquitectura, derecho y negocios corporativos.',
    carreras: ['Comunicación', 'Ingeniería Industrial', 'Administración', 'Derecho', 'Arquitectura'],
    becas: ['Escalas Socioeconómicas Diferenciadas', 'Beca de Rendimiento Académico'],
    admision: 'Examen de Admisión y Pre Lima 2026.',
    website: 'https://www.ulima.edu.pe/',
    featured: false
  },
  {
    id: 'uni-11',
    name: 'Universidad Peruana de Ciencias Aplicadas',
    acronym: 'UPC',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Lima',
    regionsAvailable: ['Lima'],
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial y Semipresencial',
    description: 'Pionera en acreditaciones internacionales WASC en el Perú con campus modernos y enfoque en innovación global.',
    carreras: ['Ingeniería de Software', 'Medicina', 'Diseño Profesional Gráfico', 'Negocios Internacionales'],
    becas: ['Beca 18 Pronabec', 'Beca Socioeconómica', 'Descuento por Excelencia Académica'],
    admision: 'Admisión Continua 2026.',
    website: 'https://www.upc.edu.pe/',
    featured: false
  },
  {
    id: 'uni-12',
    name: 'Universidad de Ingeniería y Tecnología',
    acronym: 'UTEC',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Lima',
    regionsAvailable: ['Lima'],
    logo: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'Universidad de vanguardia tecnológica inspirada en las mejores escuelas de ingeniería de EE.UU. con convenios con MIT y Harvard.',
    carreras: ['Ciencia de la Computación', 'Ingeniería Mecatrónica', 'Bioingeniería', 'Ciencia de Datos'],
    becas: ['Beca Talento BCP', 'Beca UTEC Transformadores', 'Beca 18 Pronabec'],
    admision: 'Evaluación de Rendimiento y Examen de Admisión 2026.',
    website: 'https://utec.edu.pe/',
    featured: true
  },
  {
    id: 'uni-13',
    name: 'Universidad Nacional de San Agustín de Arequipa',
    acronym: 'UNSA',
    type: 'Universidad Pública',
    typeCategory: 'publica',
    region: 'Arequipa',
    regionsAvailable: ['Arequipa'],
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'La principal universidad pública del sur del Perú con más de 190 años de historia, parques científicos y centros de investigación minera.',
    carreras: ['Ingeniería de Minas', 'Medicina Humana', 'Ingeniería Geológica', 'Derecho', 'Ingeniería Química'],
    becas: ['Beca Permanencia Pronabec', 'Bolsa de Trabajo y Comedor Universitario Gratuito'],
    admision: 'Procesos de Admisión Ordinario y CEPRUNSA 2026.',
    website: 'https://www.unsa.edu.pe/',
    featured: true
  },
  {
    id: 'uni-14',
    name: 'Universidad Nacional San Antonio Abad del Cusco',
    acronym: 'UNSAAC',
    type: 'Universidad Pública',
    typeCategory: 'publica',
    region: 'Cusco',
    regionsAvailable: ['Cusco'],
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'La tricentenaria casa de estudios del Cusco, cuna de profesionales en arqueología, turismo, ingeniería civil y ciencias agrarias.',
    carreras: ['Arqueología', 'Turismo', 'Ingeniería Civil', 'Medicina Humana', 'Biología'],
    becas: ['Beca 18 Pronabec', 'Beca Residencia y Comedor Universitario'],
    admision: 'Examen de Primera Opción y Ordinario 2026.',
    website: 'https://www.unsaac.edu.pe/',
    featured: true
  },
  {
    id: 'uni-15',
    name: 'Universidad Nacional de Trujillo',
    acronym: 'UNT',
    type: 'Universidad Pública',
    typeCategory: 'publica',
    region: 'La Libertad',
    regionsAvailable: ['La Libertad'],
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'Fundada por el Libertador Simón Bolívar, es el centro académico más representativo de la costa norte del Perú.',
    carreras: ['Medicina Humana', 'Ingeniería Industrial', 'Derecho', 'Ciencias de la Comunicación'],
    becas: ['Beca Pronabec', 'Intercambios Internacionales con Europa'],
    admision: 'Concurso de Admisión Ordinario 2026.',
    website: 'https://unitru.edu.pe/',
    featured: false
  },
  {
    id: 'uni-16',
    name: 'Universidad Católica San Pablo',
    acronym: 'UCSP',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Arequipa',
    regionsAvailable: ['Arequipa'],
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'Reconocida en el sur por sus carreras de Ciencia de la Computación, Ingeniería Electrónica y formación humanística integral.',
    carreras: ['Ciencia de la Computación', 'Ingeniería Industrial', 'Derecho', 'Psicología'],
    becas: ['Beca San Pablo', 'Beca BCP', 'Beca Pronabec 18'],
    admision: 'Admisión Continua y Examen de Aptitud 2026.',
    website: 'https://ucsp.edu.pe/',
    featured: false
  },
  {
    id: 'uni-17',
    name: 'SENATI - Sede Nacional',
    acronym: 'SENATI',
    type: 'Instituto de Educación Superior Tecnológica',
    typeCategory: 'instituto',
    region: 'Nacional',
    regionsAvailable: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Cusco', 'Huancayo'],
    logo: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Dual Presencial y Virtual',
    description: 'La institución de formación técnica profesional con mayor demanda y empleabilidad del país (9 de cada 10 egresados trabajan en su especialidad).',
    carreras: ['Mecatrónica Industrial', 'Desarrollo de Software', 'Mecánica Automotriz', 'Electricidad Industrial'],
    becas: ['Beca 18 Pronabec - Modalidad Técnica', 'Beca Dual Empresarial'],
    admision: 'Convocatoria de Admisión 2026 abierta en todas las sedes del Perú.',
    website: 'https://www.senati.edu.pe/',
    featured: true
  },
  {
    id: 'uni-18',
    name: 'Universidad Nacional del Centro del Perú',
    acronym: 'UNCP',
    type: 'Universidad Pública',
    typeCategory: 'publica',
    region: 'Junín',
    regionsAvailable: ['Junín', 'Huancayo'],
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'Centro científico y tecnológico de la sierra central del Perú con facultades de ingeniería metalúrgica, minas, zootecnia y medicina.',
    carreras: ['Ingeniería Metalúrgica y de Materiales', 'Medicina Humana', 'Agronomía', 'Ingeniería Civil'],
    becas: ['Beca Permanencia Pronabec', 'Residencia y Comedor Gratuito'],
    admision: 'Examen de Admisión General 2026.',
    website: 'https://uncp.edu.pe/',
    featured: false
  },
  {
    id: 'uni-19',
    name: 'Universidad Nacional del Altiplano',
    acronym: 'UNA PUNO',
    type: 'Universidad Pública',
    typeCategory: 'publica',
    region: 'Puno',
    regionsAvailable: ['Puno'],
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'Institución líder en la meseta del Collao en investigación de camélidos sudamericanos, energías renovables en altura e ingeniería de minas.',
    carreras: ['Medicina Veterinaria y Zootecnia', 'Ingeniería Estadística e Informática', 'Medicina Humana'],
    becas: ['Beca Pronabec Comunidades Originarias', 'Comedor Universitario'],
    admision: 'Examen General de Admisión 2026.',
    website: 'https://portal.unap.edu.pe/',
    featured: false
  },
  {
    id: 'uni-20',
    name: 'Universidad San Ignacio de Loyola',
    acronym: 'USIL',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Lima',
    regionsAvailable: ['Lima', 'Cusco'],
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial y Virtual',
    description: 'Enfocada en emprendimiento, gastronomía internacional, hotelería y gestión empresarial con doble grado en EE.UU. (San Ignacio University Miami).',
    carreras: ['Arte Culinario', 'Administración Hotelera', 'International Business', 'Marketing'],
    becas: ['Beca de Emprendimiento', 'Beca 18 Pronabec', 'Beca Excelencia'],
    admision: 'Admisión Regular 2026.',
    website: 'https://usil.edu.pe/',
    featured: false
  },
  {
    id: 'uni-21',
    name: 'Universidad San Martín de Porres',
    acronym: 'USMP',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Lima',
    regionsAvailable: ['Lima', 'Chiclayo', 'Arequipa'],
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial y Semipresencial',
    description: 'Destacada por sus facultades de Ciencias de la Comunicación, Turismo y Psicología, y Medicina Humana acreditadas internacionalmente.',
    carreras: ['Medicina Humana', 'Derecho', 'Ciencias de la Comunicación', 'Odontología'],
    becas: ['Beca de Estímulo al Mérito', 'Beca Pronabec'],
    admision: 'Concurso de Admisión USMP 2026.',
    website: 'https://www.usmp.edu.pe/',
    featured: false
  },
  {
    id: 'uni-22',
    name: 'Universidad Nacional de la Amazonía Peruana',
    acronym: 'UNAP',
    type: 'Universidad Pública',
    typeCategory: 'publica',
    region: 'Loreto',
    regionsAvailable: ['Loreto', 'Iquitos'],
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'El referente universitario del oriente peruano en biodiversidad amazónica, ecología tropical, acuicultura y silvicultura.',
    carreras: ['Ingeniería Forestal', 'Acuicultura', 'Medicina Humana', 'Biología Tropical'],
    becas: ['Beca Pronabec Comunidades Nativas', 'Comedor Universitario Gratuito'],
    admision: 'Admisión Descentralizada 2026.',
    website: 'https://www.unapiquitos.edu.pe/',
    featured: false
  },
  {
    id: 'uni-23',
    name: 'CIBERTEC - Educación Tecnológica',
    acronym: 'CIBERTEC',
    type: 'Instituto de Educación Superior Tecnológica',
    typeCategory: 'instituto',
    region: 'Nacional',
    regionsAvailable: ['Lima', 'Arequipa', 'Trujillo'],
    logo: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial y Virtual',
    description: 'Institución líder en carreras de tecnología, diseño, computación y negocios digitales con convenios de convalidación universitaria.',
    carreras: ['Desarrollo de Software', 'Ciberseguridad', 'Diseño Gráfico Digital', 'Redes y Comunicaciones'],
    becas: ['Beca 18 Pronabec - Modalidad Institutos', 'Beca de Continuidad'],
    admision: 'Inscripciones Abiertas 2026.',
    website: 'https://www.cibertec.edu.pe/',
    featured: true
  },
  {
    id: 'uni-24',
    name: 'Universidad Católica de Santa María',
    acronym: 'UCSM',
    type: 'Universidad Privada',
    typeCategory: 'privada',
    region: 'Arequipa',
    regionsAvailable: ['Arequipa'],
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop&q=80',
    modalidad: 'Presencial',
    description: 'La primera universidad privada de provincias del Perú con facultades de medicina, ingeniería biotecnológica, arquitectura y derecho.',
    carreras: ['Medicina Humana', 'Biotecnología', 'Arquitectura', 'Ingeniería Mecánica Eléctrica'],
    becas: ['Beca Santa María', 'Beca BCP', 'Beca Pronabec 18'],
    admision: 'Proceso de Admisión Ordinario 2026.',
    website: 'https://www.ucsm.edu.pe/',
    featured: false
  }
];

let added = 0;
for (const u of newUniversities) {
  if (!existingIds.has(u.id)) {
    existing.push(u);
    existingIds.add(u.id);
    added++;
  }
}

const fileContent = `export const universitiesData = ${JSON.stringify(existing, null, 2)};\n`;
fs.writeFileSync(path.join(rootDir, 'src', 'data', 'universitiesData.js'), fileContent, 'utf-8');

console.log(`Added ${added} universities! Total: ${existing.length}`);
