import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

import { opportunitiesDetailData as existing } from '../src/data/opportunitiesDetailData.js';

const existingIds = new Set(existing.map(o => o.id));

const moreItems = [
  // 4 more scholarships (Total 25)
  {
    id: 'beca-eiffel-francia-2026',
    title: 'Beca Eiffel de Excelencia - Maestrías y Doctorados en Francia',
    organization: 'Ministerio para Europa y de Asuntos Exteriores de Francia (Campus France)',
    category: 'scholarship',
    type: 'Maestría y Doctorado en Universidades Francesas',
    typeCategory: 'postgraduate',
    ageRange: 'over25',
    ageRangeLabel: 'Hasta 27 años (Máster) / 32 (Doctorado)',
    coverage: 'full',
    coverageLabel: '1,181€ a 1,700€ Mensuales + Pasajes y Seguro',
    modality: 'onsite',
    location: 'Francia (París, Lyon, Toulouse, Estrasburgo)',
    deadline: '2026-11-10',
    description: 'Permite a talentos peruanos formarse en ingeniería, economía, derecho y ciencias exactas en las Grandes Écoles y universidades públicas francesas.',
    image_url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.campusfrance.org/es/el-programa-de-becas-eiffel',
    featured: true,
    requirements: ['Excelencia académica demostrada.', 'Admisión en una universidad francesa elegible.'],
    benefits: ['Asignación mensual completa.', 'Pasaje aéreo internacional y cobertura de seguridad social.']
  },
  {
    id: 'beca-fundacion-botin-2026',
    title: 'Programa para el Fortalecimiento de la Función Pública en América Latina',
    organization: 'Fundación Botín (España)',
    category: 'scholarship',
    type: 'Pasantía de Liderazgo y Gestión Pública',
    typeCategory: 'undergraduate',
    ageRange: '18to25',
    ageRangeLabel: 'Universitarios de 19 a 24 años',
    coverage: 'full',
    coverageLabel: '100% Financiado en España, Colombia y Brasil',
    modality: 'onsite',
    location: 'España (Madrid, Santander, Salamanca) y Río de Janeiro',
    deadline: '2026-05-30',
    description: 'Formación intensiva de liderazgo cívico para universitarios con vocación de servicio público y transformación social en sus países.',
    image_url: 'https://images.unsplash.com/photo-1525921429624-479b6a26d84d?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://fundacionbotin.org/',
    featured: false,
    requirements: ['Estar cursando estudios universitarios con alto expediente académico.', 'Vocación demostrada de servicio social.'],
    benefits: ['Traslados internacionales, alojamiento, manutención y programa formativo completo.']
  },
  {
    id: 'beca-turquia-2026',
    title: 'Türkiye Scholarships - Pregrado y Posgrado en Turquía',
    organization: 'Gobierno de Turquía (YTB)',
    category: 'scholarship',
    type: 'Carreras Universitarias y Maestrías',
    typeCategory: 'undergraduate',
    ageRange: 'all',
    ageRangeLabel: 'Hasta 21 (Pregrado) / 30 (Máster)',
    coverage: 'full',
    coverageLabel: '100% Cobertura Integral + Residencia Universitaria',
    modality: 'onsite',
    location: 'Turquía (Estambul, Ankara, Esmirna)',
    deadline: '2026-06-20',
    description: 'Financiamiento completo del gobierno turco en universidades de primer nivel con residencia, seguro médico y un año de aprendizaje del idioma turco.',
    image_url: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.turkiyeburslari.gov.tr/',
    featured: false,
    requirements: ['Promedio superior al 70% o tercio superior.', 'Pasaporte vigente.'],
    benefits: ['Matrícula universitaria completa, alojamiento en residencia, estipendio mensual y pasajes de avión.']
  },
  {
    id: 'beca-auip-posgrado-2026',
    title: 'Becas de Movilidad y Posgrado AUIP 2026',
    organization: 'Asociación Universitaria Iberoamericana de Postgrado (AUIP)',
    category: 'scholarship',
    type: 'Maestrías y Doctorados Iberoamericanos',
    typeCategory: 'postgraduate',
    ageRange: 'over25',
    ageRangeLabel: 'Bachilleres y Profesionales',
    coverage: 'partial',
    coverageLabel: 'Bolsa de Viaje y Matrícula Reducida',
    modality: 'onsite',
    location: 'España, Portugal y Latinoamérica',
    deadline: '2026-07-20',
    description: 'Becas de movilidad académica y ayuda económica para cursar másteres oficiales en universidades asociadas a la red AUIP en Andalucía y el resto de España.',
    image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.auip.org/',
    featured: false,
    requirements: ['Estar vinculado a una universidad peruana miembro de AUIP.'],
    benefits: ['Bolsa de viaje de hasta 1,200 euros más exención de tasas académicas.']
  },

  // 6 more jobs (Total 24)
  {
    id: 'empleo-redactor-copywriter-2026',
    title: 'Redactor Creativo & Copywriter Digital Junior',
    organization: 'Agencia de Contenidos & E-commerce',
    category: 'job',
    type: 'Puesto en Planilla Remota',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '18 a 28 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,500 a S/ 1,800 + Home Office',
    modality: 'virtual',
    location: '100% Remoto (Perú)',
    deadline: '2026-09-18',
    description: 'Redacción de artículos de blog optimizados para SEO, correos de email marketing persuasivos y guiones para videos de redes sociales.',
    image_url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Excelente ortografía y redacción en español.', 'Creatividad para redactar textos de venta y storytelling.'],
    benefits: ['Trabajo 100% desde casa.', 'Flexibilidad de horarios.']
  },
  {
    id: 'empleo-analista-creditos-junior-2026',
    title: 'Analista de Créditos y Finanzas MYPE Junior',
    organization: 'Caja Municipal de Ahorro y Crédito',
    category: 'job',
    type: 'Empleo Financiero en Planilla',
    typeCategory: 'junior',
    ageRange: '18to25',
    ageRangeLabel: '20 a 29 años',
    coverage: 'full',
    coverageLabel: 'Básico S/ 1,600 + Movilidad + Comisiones',
    modality: 'onsite',
    location: 'Lima (Conos) y Provincias (Arequipa, Piura, Huancayo)',
    deadline: '2026-09-30',
    description: 'Evaluación de solicitudes de créditos para microempresarios, visitas de campo para verificación de negocios y recuperación de cartera.',
    image_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: true,
    requirements: ['Egresado técnico o universitario de Finanzas, Economía, Contabilidad o Administración.', 'Disponibilidad para trabajo de campo.'],
    benefits: ['Ingreso a planilla con bonos por colocación de créditos sin tope.', 'Seguro de vida ley y capacitación constante.']
  },
  {
    id: 'empleo-supervisor-retail-junior-2026',
    title: 'Supervisor Junior de Tienda & Experiencia del Cliente Retail',
    organization: 'Cadena de Tiendas de Moda & Calzado',
    category: 'job',
    type: 'Puesto en Planilla Completa',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '20 a 28 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,700 a S/ 2,100 + Bonos de Tienda',
    modality: 'onsite',
    location: 'Centros Comerciales (Jockey Plaza, Mall del Sur, MegaPlaza)',
    deadline: '2026-08-30',
    description: 'Supervisión de equipos de ventas, control de caja, visual merchandising y cumplimiento de metas de facturación en tienda.',
    image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Estudios concluidos o en curso en Administración, Marketing o carreras afines.', 'Liderazgo y manejo de equipos.'],
    benefits: ['Planilla completa, descuentos en productos de la marca y línea de ascenso a Administrador de Tienda.']
  },
  {
    id: 'empleo-auxiliar-laboratorio-control-2026',
    title: 'Auxiliar de Laboratorio & Control de Calidad',
    organization: 'Laboratorio Farmacéutico & Cosmético Nacional',
    category: 'job',
    type: 'Puesto Fijo en Planta Farmacéutica',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '19 a 28 años',
    coverage: 'full',
    coverageLabel: 'S/ 1,600 en Planilla + Alimentación en Planta',
    modality: 'onsite',
    location: 'Lima (Ate / Santa Anita)',
    deadline: '2026-09-15',
    description: 'Toma de muestras en línea de producción, ensayos físico-químicos elementales, calibración de balanzas y registro de BPM (Buenas Prácticas de Manufactura).',
    image_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Técnico egresado de Farmacia, Química Industrial o Control de Calidad.'],
    benefits: ['Ingreso a planilla con CTS y gratificaciones.', 'Alimentación cubierta al 100%.']
  },
  {
    id: 'empleo-coordinador-despacho-ecommerce-2026',
    title: 'Coordinador Junior de Despacho & Última Milla (E-Commerce)',
    organization: 'Operador Logístico & Courier Express',
    category: 'job',
    type: 'Puesto Operativo en Planilla',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '19 a 28 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,550 a S/ 1,900 + Bono de Eficiencia',
    modality: 'onsite',
    location: 'Lima (Cercado de Lima / La Victoria)',
    deadline: '2026-08-25',
    description: 'Monitoreo de rutas de repartidores, gestión de pedidos pendientes en sistema ERP, resolución de incidencias en entregas y contacto con clientes.',
    image_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Experiencia previa de 6 meses en almacén, logística o atención al cliente.'],
    benefits: ['Planilla de ley completa.', 'Horas extras remuneradas.']
  },
  {
    id: 'empleo-asistente-comercio-exterior-2026',
    title: 'Asistente de Importaciones y Comercio Exterior Junior',
    organization: 'Agencia de Aduanas y Carga Internacional',
    category: 'job',
    type: 'Empleo en Planilla de Régimen General',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '19 a 27 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,600 a S/ 2,000 + Capacitaciones Aduaneras',
    modality: 'onsite',
    location: 'Callao (Cerca al Aeropuerto y Puerto)',
    deadline: '2026-09-20',
    description: 'Revisión de documentos de importación (B/L, facturas comerciales, certificados de origen), coordinación con navieras y seguimiento de desaduanamiento.',
    image_url: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: true,
    requirements: ['Egresado de Administración de Negocios Internacionales o Comercio Exterior.', 'Conocimiento básico de Incoterms y régimen aduanero.'],
    benefits: ['Línea de carrera hacia Liquidador de Aduanas.', 'Planilla completa.']
  },

  // 6 more competitions (Total 21)
  {
    id: 'concurso-ideaton-educacion-rural-2026',
    title: 'Ideatón por la Educación Rural en el Perú',
    organization: 'UNESCO Perú & Ministerio de Educación',
    category: 'competition',
    type: 'Concurso de Proyectos de Innovación Social',
    typeCategory: 'education',
    ageRange: 'all',
    ageRangeLabel: '16 a 29 años',
    coverage: 'full',
    coverageLabel: 'Capital Semilla de S/ 25,000 + Asistencia Técnica',
    modality: 'virtual',
    location: 'Nacional',
    deadline: '2026-09-28',
    description: 'Desarrolla soluciones tecnológicas o pedagógicas que mejoren el acceso al aprendizaje en comunidades altoandinas y amazónicas sin conectividad estable.',
    image_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.unesco.org/es/fieldoffice/lima',
    featured: true,
    requirements: ['Equipos de 2 a 4 jóvenes residentes en Perú.', 'Propuesta orientada a escuelas rurales públicas.'],
    benefits: ['Fondo económico para el piloto.', 'Acompañamiento por especialistas de UNESCO.']
  },
  {
    id: 'concurso-appcircus-lima-2026',
    title: 'AppCircus Lima - Competencia de Aplicaciones Móviles Innovadoras',
    organization: 'AppCircus Global & HUB UDEP',
    category: 'competition',
    type: 'Concurso de Desarrollo de Software Móvil',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Desarrolladores y Emprendedores',
    coverage: 'full',
    coverageLabel: 'Nominación a los Mobile Premier Awards de Barcelona',
    modality: 'hybrid',
    location: 'Lima (Presentación en vivo / Pitch)',
    deadline: '2026-10-12',
    description: 'Presenta tu aplicación móvil (iOS o Android) en 3 minutos de pitch ante un jurado de inversionistas y líderes de la industria tecnológica.',
    image_url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://appcircus.com/',
    featured: false,
    requirements: ['App móvil funcional publicada o en fase beta avanzada.'],
    benefits: ['Exposición internacional.', 'Pase para competir en el Mobile World Congress de Barcelona.']
  },
  {
    id: 'concurso-reto-agua-rural-2026',
    title: 'Reto Agua y Saneamiento Rural - Innovación Tecnológica',
    organization: 'Ministerio de Vivienda, Construcción y Saneamiento (MVCS)',
    category: 'competition',
    type: 'Concurso Estatal de Soluciones Hídricas',
    typeCategory: 'innovation',
    ageRange: 'all',
    ageRangeLabel: 'Universitarios y Profesionales',
    coverage: 'full',
    coverageLabel: 'Premios de S/ 50,000 en Financiamiento de Prototipos',
    modality: 'hybrid',
    location: 'Nacional',
    deadline: '2026-10-20',
    description: 'Propuestas de bajo costo para purificación de agua, captación de niebla y saneamiento en zonas rurales dispersas del país.',
    image_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.gob.pe/vivienda',
    featured: false,
    requirements: ['Proyectos viables técnicamente con materiales accesibles.'],
    benefits: ['Financiamiento del prototipo en una comunidad piloto.']
  },
  {
    id: 'concurso-creatividad-empresarial-2026',
    title: 'Premio Creatividad Empresarial - Categoría Jóvenes Emprendedores',
    organization: 'Universidad Peruana de Ciencias Aplicadas (UPC)',
    category: 'competition',
    type: 'Premio de Innovación Empresarial de Mayor Prestigio',
    typeCategory: 'innovation',
    ageRange: 'all',
    ageRangeLabel: 'Emprendedores peruanos',
    coverage: 'full',
    coverageLabel: 'Trofeo Oficial + Beca de Posgrado en la UPC',
    modality: 'virtual',
    location: 'Lima (Ceremonia de Gala)',
    deadline: '2026-09-15',
    description: 'El reconocimiento más importante a la innovación corporativa y emprendedora en el Perú durante más de 25 años.',
    image_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://creatividadempresarial.upc.edu.pe/',
    featured: true,
    requirements: ['Productos, servicios o modelos de negocio novedosos lanzados en los últimos dos años.'],
    benefits: ['Máxima reputación de marca a nivel nacional.', 'Beca completa para programas de posgrado en la Escuela de Postgrado UPC.']
  },
  {
    id: 'concurso-campodónico-sociedad-2026',
    title: 'Premio Esteban Campodónico - Servicios a la Sociedad Peruana',
    organization: 'Fundación Clover & Universidad de Piura (UDEP)',
    category: 'competition',
    type: 'Premio Humanitario y Social',
    typeCategory: 'social',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: 'USD 50,000 en Efectivo + Medalla de Honor',
    modality: 'virtual',
    location: 'Lima / Piura',
    deadline: '2026-06-30',
    description: 'Premia a personas e instituciones que hayan realizado una labor altruista sobresaliente y sostenida en beneficio de las poblaciones vulnerables del Perú.',
    image_url: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://estebancampodonico.org/',
    featured: false,
    requirements: ['Candidaturas respaldadas por instituciones reconocidas.'],
    benefits: ['Premio económico de 50,000 dólares estadounidenses de libre disponibilidad.']
  },
  {
    id: 'concurso-hackathon-amazonia-2026',
    title: 'Hackathon por la Amazonía & Monitoreo Forestal Satelital',
    organization: 'SERFOR (Ministerio de Desarrollo Agrario) & WWF Perú',
    category: 'competition',
    type: 'Hackathon Ambiental Tech',
    typeCategory: 'hackathon',
    ageRange: 'all',
    ageRangeLabel: 'Jóvenes de 18 a 30 años',
    coverage: 'full',
    coverageLabel: 'S/ 30,000 en Premios + Viaje a la Reserva Nacional Tambopata',
    modality: 'hybrid',
    location: 'Puerto Maldonado (Madre de Dios) / Virtual',
    deadline: '2026-10-10',
    description: 'Crea algoritmos de visión por computadora e inteligencia artificial para detectar alertas tempranas de deforestación y minería ilegal en la selva peruana.',
    image_url: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.serfor.gob.pe/',
    featured: true,
    requirements: ['Equipos interdisciplinarios en ciencia de datos, sensores remotos y biología.'],
    benefits: ['Premios en efectivo.', 'Expedición científica guiada a la selva amazónica.']
  },

  // 5 more volunteering (Total 22)
  {
    id: 'voluntariado-aldeas-sos-2026',
    title: 'Aldeas Infantiles SOS Perú - Mentoría y Cuidado Infantil',
    organization: 'Aldeas Infantiles SOS Perú',
    category: 'volunteer',
    type: 'Voluntariado Social y Pediátrico',
    typeCategory: 'social',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: 'Certificación Oficial de Voluntariado',
    modality: 'onsite',
    location: 'Sedes en Zárate, Carabayllo, Callao, Chiclayo, Cusco, Arequipa',
    deadline: '2026-10-25',
    description: 'Acompaña el desarrollo de niñas, niños y adolescentes en acogimiento familiar a través de talleres de lectura, juegos y refuerzo de valores.',
    image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.aldeasinfantiles.org.pe/',
    featured: true,
    requirements: ['Compromiso mínimo de 3 meses.', 'No registrar antecedentes y aprobar evaluación psicológica básica.'],
    benefits: ['Capacitación en derechos de la infancia y protección infantil.', 'Constancia oficial de horas.']
  },
  {
    id: 'voluntariado-magia-cancer-2026',
    title: 'Asociación de Voluntarias MAGIA por los Niños con Cáncer',
    organization: 'Asociación MAGIA',
    category: 'volunteer',
    type: 'Voluntariado en Salud y Albergue',
    typeCategory: 'health',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: 'Participación Acreditada',
    modality: 'onsite',
    location: 'Casa Magia (Surquillo, Lima)',
    deadline: '2026-09-15',
    description: 'Brinda momentos de alegría, lectura y manualidades a niños de provincias que reciben tratamiento oncológico en el INEN y se hospedan en Casa Magia.',
    image_url: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://lamagiaquesana.org/',
    featured: false,
    requirements: ['Calidez humana, empatía y disponibilidad para turnos de acompañamiento.'],
    benefits: ['Experiencia humana transformadora.', 'Constancia de voluntariado en salud.']
  },
  {
    id: 'voluntariado-greenpeace-peru-2026',
    title: 'Greenpeace Andino Perú - Voluntariado de Activismo Ambiental',
    organization: 'Greenpeace Perú',
    category: 'volunteer',
    type: 'Voluntariado Ecológico y Campañas Ciudadanas',
    typeCategory: 'environment',
    ageRange: 'all',
    ageRangeLabel: '16 a 29 años',
    coverage: 'full',
    coverageLabel: 'Acreditación Internacional Greenpeace',
    modality: 'hybrid',
    location: 'Lima y Principales Regiones Costeras',
    deadline: '2026-11-15',
    description: 'Campañas de concientización sobre energías renovables, cese del uso de plásticos y protección de la reserva de Paracas y los glaciares peruanos.',
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.greenpeace.org/peru/',
    featured: false,
    requirements: ['Interés activo en causas ecológicas y justicia climática.'],
    benefits: ['Talleres de activismo pacífico y liderazgo ambiental.', 'Insignia y certificado Greenpeace.']
  },
  {
    id: 'voluntariado-vidawasi-cusco-2026',
    title: 'Vidawasi Perú - Voluntariado en Ciudad Pediátrica Valle Sagrado',
    organization: 'Fundación Vidawasi',
    category: 'volunteer',
    type: 'Voluntariado Comunitario en Salud Rural',
    typeCategory: 'health',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: 'Alojamiento en la Ciudadela para Voluntarios de Fuera de Cusco',
    modality: 'onsite',
    location: 'Valle Sagrado de los Incas (Urubamba, Cusco)',
    deadline: '2026-08-31',
    description: 'Colabora en la primera ciudadela de salud infantil del Perú que brinda atención médica especializada a miles de niños de comunidades andinas.',
    image_url: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://vidawasiperu.org/',
    featured: true,
    requirements: ['Disponibilidad para estancia mínima de 2 semanas en el Valle Sagrado.'],
    benefits: ['Alojamiento comunitario en la ciudadela Vidawasi.', 'Certificado oficial de servicio humanitario.']
  },
  {
    id: 'voluntariado-kusi-kawsay-2026',
    title: 'Kusi Kawsay - Talleres Educativos y Revaloración Cultural Andina',
    organization: 'Asociación Kusi Kawsay (Písac, Cusco)',
    category: 'volunteer',
    type: 'Voluntariado Intercultural',
    typeCategory: 'education',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: 'Participación Comunitaria Acreditada',
    modality: 'onsite',
    location: 'Písac (Cusco)',
    deadline: '2026-09-30',
    description: 'Apoyo en talleres de arte tradicional, agricultura ecológica andina, música y reforzamiento del idioma quechua para niños y jóvenes de comunidades originarias.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://kusikawsay.org/',
    featured: false,
    requirements: ['Respeto por la cosmovisión andina y vocación educativa.'],
    benefits: ['Inmersión cultural en el Valle Sagrado.', 'Constancia de voluntariado intercultural.']
  }
];

let addedFinal = 0;
for (const item of moreItems) {
  if (!existingIds.has(item.id)) {
    existing.push(item);
    existingIds.add(item.id);
    addedFinal++;
  }
}

// Final check: fix all BCP links
existing.forEach(item => {
  if (item.external_link && item.external_link.includes('viabcp.com/becas-bcp')) {
    item.external_link = 'https://www.viabcp.com/becasbcp';
  }
});

const fileContent = `export const opportunitiesDetailData = ${JSON.stringify(existing, null, 2)};\n`;
fs.writeFileSync(path.join(rootDir, 'src', 'data', 'opportunitiesDetailData.js'), fileContent, 'utf-8');

console.log(`Added ${addedFinal} final opportunities!`);
console.log(`Grand total opportunities: ${existing.length}`);
