import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

import { opportunitiesDetailData as existing } from '../src/data/opportunitiesDetailData.js';

const existingIds = new Set(existing.map(o => o.id));

const moreOpportunities = [
  // ─── CURSOS (Target: 25+) ───
  {
    id: 'curso-platzi-programacion-basica-2026',
    title: 'Curso Gratuito de Programación Básica (JavaScript / Algoritmos)',
    organization: 'Platzi Becas & Fundación Telefónica',
    category: 'course',
    type: 'Curso Virtual Certificado',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: '100% Gratuito y Certificado',
    modality: 'virtual',
    location: '100% Online',
    deadline: '2026-12-31',
    description: 'Aprende a programar desde cero sin conocimientos previos. Crea tus primeros videojuegos, algoritmos y aplicaciones interactivas en JavaScript y HTML5.',
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://platzi.com/cursos/programacion-basica/',
    featured: true,
    requirements: ['Computadora o celular con conexión a internet.'],
    benefits: ['Certificado digital al aprobar el examen final.', 'Comunidad de estudiantes en línea.']
  },
  {
    id: 'curso-senati-virtual-electricidad-2026',
    title: 'Fundamentos de Electricidad y Electrónica Industrial',
    organization: 'SENATI Cursos Abiertos',
    category: 'course',
    type: 'Curso Técnico Virtual',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: '16 años a más',
    coverage: 'full',
    coverageLabel: 'Acceso Libre y Gratuito',
    modality: 'virtual',
    location: 'Campus Online SENATI',
    deadline: '2026-10-31',
    description: 'Conceptos clave de circuitos eléctricos, instrumentos de medición (multímetro), seguridad en instalaciones industriales y diagnóstico de fallas.',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.senati.edu.pe/',
    featured: false,
    requirements: ['Interés en carreras técnicas de electricidad e industria.'],
    benefits: ['Constancia de participación emitida por SENATI.']
  },
  {
    id: 'curso-mtpe-capacitate-logistica-2026',
    title: 'Auxiliar de Almacén, Inventarios y Logística Moderna',
    organization: 'MTPE (Programa CAPACÍTATE Perú)',
    category: 'course',
    type: 'Curso Ocupacional Certificado por el Estado',
    typeCategory: 'business',
    ageRange: '18to25',
    ageRangeLabel: '18 a 29 años',
    coverage: 'full',
    coverageLabel: '100% Gratuito y Válido para Planilla',
    modality: 'virtual',
    location: 'Nacional (Plataforma MTPE)',
    deadline: '2026-09-20',
    description: 'Capacitación oficial del Ministerio de Trabajo en control de inventarios, picking, packing, seguridad en almacenes y sistemas WMS.',
    image_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/capacitacion-laboral/',
    featured: true,
    requirements: ['Secundaria completa.', 'DNI peruano o carné de extranjería.'],
    benefits: ['Certificado oficial a nombre del MTPE.', 'Vinculación directa a la bolsa de trabajo Empleos Perú.']
  },
  {
    id: 'curso-cisco-ciberseguridad-junior-2026',
    title: 'Ciberseguridad Junior & Defensa de Redes',
    organization: 'Cisco Networking Academy',
    category: 'course',
    type: 'Curso Especializado de Ciberdefensa',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: '100% Gratuito',
    modality: 'virtual',
    location: 'NetAcad Virtual',
    deadline: '2026-11-15',
    description: 'Comprende los vectores de ataque más comunes, ingeniería social, malware, firewalls y cómo defender activos digitales de empresas.',
    image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.netacad.com/',
    featured: false,
    requirements: ['Conocimientos elementales de computación e internet.'],
    benefits: ['Badge oficial de Cisco.', 'Preparación para el examen Certified Support Technician (CCST).']
  },
  {
    id: 'curso-coursera-finanzas-personales-2026',
    title: 'Finanzas Personales y Presupuesto para Jóvenes',
    organization: 'Universidad Nacional Autónoma de México & Coursera',
    category: 'course',
    type: 'Curso de Educación Financiera',
    typeCategory: 'business',
    ageRange: 'all',
    ageRangeLabel: '16 a 29 años',
    coverage: 'full',
    coverageLabel: 'Acceso Gratuito a Todo el Contenido',
    modality: 'virtual',
    location: 'Coursera en Español',
    deadline: '2026-12-31',
    description: 'Aprende a presupuestar tus ingresos, evitar deudas destructivas, ahorrar inteligentemente y realizar tus primeras inversiones seguras.',
    image_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.coursera.org/learn/finanzas-personales',
    featured: false,
    requirements: ['Interés en administrar y hacer crecer tu dinero.'],
    benefits: ['Herramientas y plantillas de presupuesto descargables.']
  },
  {
    id: 'curso-google-ux-design-2026',
    title: 'Certificado Profesional de Diseño de Experiencia de Usuario (UX) de Google',
    organization: 'Google Career Certificates',
    category: 'course',
    type: 'Especialización Profesional en Diseño UX/UI',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: '100% Beca de Formación',
    modality: 'virtual',
    location: 'En Línea',
    deadline: '2026-10-25',
    description: 'Domina Figma, wireframes, prototipos interactivos, investigación con usuarios y pruebas de usabilidad para diseñar apps y sitios web intuitivos.',
    image_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://grow.google/intl/es/certificates/ux-design/',
    featured: true,
    requirements: ['No se requiere experiencia previa en diseño ni programación.'],
    benefits: ['Portafolio profesional con 3 proyectos terminados para postular a empleos UX.']
  },
  {
    id: 'curso-sunat-emprendedores-2026',
    title: 'Cultura Tributaria y Régimen MYPE Tributario para Jóvenes Emprendedores',
    organization: 'Instituto Aduanero y Tributario (SUNAT)',
    category: 'course',
    type: 'Curso Oficial de Gestión Tributaria',
    typeCategory: 'business',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: '100% Gratuito y Certificado por SUNAT',
    modality: 'virtual',
    location: 'Campus Virtual IAT SUNAT',
    deadline: '2026-11-10',
    description: 'Conoce cómo formalizar tu emprendimiento, emitir boletas y facturas electrónicas, deducciones de gastos y evitar sanciones tributarias.',
    image_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://unete.sunat.gob.pe/',
    featured: false,
    requirements: ['Contar con DNI y acceso a internet.'],
    benefits: ['Certificado emitido por el Instituto Aduanero y Tributario de SUNAT.']
  },

  // ─── PRÁCTICAS (Target: 25+) ───
  {
    id: 'practicas-backus-supply-2026',
    title: 'Programa de Talentos Backus AB InBev 2026 (Supply Chain & Marketing)',
    organization: 'Cervecería Backus y Johnston (AB InBev)',
    category: 'internship',
    type: 'Prácticas Pre y Profesionales en Gran Empresa',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '19 a 25 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,800 + Almuerzos + Beneficios',
    modality: 'onsite',
    location: 'Planta Ate (Lima), Arequipa, Cusco, Motupe',
    deadline: '2026-08-31',
    description: 'Rotación en líneas de producción, logística cervecera y campañas de marcas líderes en consumo masivo.',
    image_url: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.backus.pe/trabaja-con-nosotros',
    featured: true,
    requirements: ['Estudiantes de 8vo a 10mo ciclo o recién egresados de Ingeniería Industrial, Administración o afines.'],
    benefits: ['Subvención competitiva.', 'Comedor en planta cubierto.', 'Oportunidad de contratación fija.']
  },
  {
    id: 'practicas-nestle-jovenes-2026',
    title: 'Iniciativa por los Jóvenes Nestlé - Prácticas de Manufactura y Ventas',
    organization: 'Nestlé Perú S.A.',
    category: 'internship',
    type: 'Prácticas Pre-Profesionales en Alimentos',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '18 a 25 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,600 + FOLA + Comedor',
    modality: 'onsite',
    location: 'Fábrica Lima (Los Olivos / Ate)',
    deadline: '2026-09-15',
    description: 'Desarrolla tus habilidades en la empresa de alimentos más grande del mundo en áreas de calidad, producción y trade marketing.',
    image_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.nestle.com.pe/jobs',
    featured: false,
    requirements: ['Estudiantes universitarios con disponibilidad de 30 horas semanales de prácticas.'],
    benefits: ['Subvención mensual formativa.', 'Acceso a descuentos en productos Nestlé.']
  },
  {
    id: 'practicas-rimac-actuarial-2026',
    title: 'Practicante de Analítica de Datos & Riesgos de Seguros',
    organization: 'Rímac Seguros (Grupo Breca)',
    category: 'internship',
    type: 'Prácticas Pre-Profesionales en Seguros y Salud',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '18 a 24 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,550 + Seguro Médico Privado',
    modality: 'hybrid',
    location: 'San Isidro (Lima)',
    deadline: '2026-07-31',
    description: 'Análisis de siniestralidad, modelos predictivos de riesgo y automatización de reportes para el mercado asegurador peruano.',
    image_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.rimac.com.pe/',
    featured: false,
    requirements: ['Estudiantes de Ingeniería Estadística, Actuarial, Sistemas o Economía.'],
    benefits: ['Convenio formativo institucional.', 'Día libre por tu cumpleaños y horario flexible.']
  },
  {
    id: 'practicas-indecopi-legal-2026',
    title: 'Prácticas Pre y Profesionales en Protección al Consumidor y Propiedad Intelectual',
    organization: 'INDECOPI',
    category: 'internship',
    type: 'Modalidad Formativa en Entidad Pública',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '18 a 26 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,300 + Seguro FOLA',
    modality: 'hybrid',
    location: 'Sede Central San Borja (Lima)',
    deadline: '2026-08-20',
    description: 'Apoyo en análisis de reclamos de consumidores, registro de marcas, derechos de autor y patentes de invención.',
    image_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.gob.pe/indecopi',
    featured: false,
    requirements: ['Estudiantes de últimos ciclos o bachilleres de Derecho, Economía o Ing. Industrial.'],
    benefits: ['Constancia con valor oficial del Estado.', 'Capacitaciones en derecho de la competencia.']
  },
  {
    id: 'practicas-scotiabank-compliance-2026',
    title: 'Practicante de Prevención de Lavado de Activos & Cumplimiento',
    organization: 'Scotiabank Perú',
    category: 'internship',
    type: 'Prácticas Pre-Profesionales en Banca Múltiple',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '18 a 24 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,500 + Beneficios Scotiabank',
    modality: 'hybrid',
    location: 'Torre Scotiabank (San Isidro, Lima)',
    deadline: '2026-09-05',
    description: 'Monitoreo de transacciones financieras, verificación de listas de cumplimiento internacional y elaboración de alertas preventivas.',
    image_url: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.scotiabank.com.pe/',
    featured: false,
    requirements: ['Estudiantes de Derecho, Contabilidad, Finanzas o Administración.'],
    benefits: ['Formación en estándares bancarios canadienses e internacionales.']
  },
  {
    id: 'practicas-deloitte-consulting-2026',
    title: 'Trainee en Consultoría Tecnológica & Ciberseguridad Deloitte',
    organization: 'Deloitte Perú',
    category: 'internship',
    type: 'Prácticas Profesionales en Consultoría Global',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '20 a 26 años',
    coverage: 'full',
    coverageLabel: 'Subvención de Mercado + Plan de Formación Global',
    modality: 'hybrid',
    location: 'Lima (San Isidro / Remoto)',
    deadline: '2026-09-30',
    description: 'Participa en proyectos de arquitectura cloud, gobernanza de datos y auditoría de sistemas para clientes bancarios y mineros.',
    image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www2.deloitte.com/pe/es.html',
    featured: true,
    requirements: ['Egresados o bachilleres de Ingeniería de Sistemas, Telecomunicaciones o Informática.'],
    benefits: ['Certificaciones tecnológicas patrocinadas.', 'Movilidad internacional a mediano plazo.']
  },
  {
    id: 'practicas-belcorp-trade-2026',
    title: 'Practicante de Trade Marketing & Canal Digital',
    organization: 'Belcorp (L’Bel, Ésika, Cyzone)',
    category: 'internship',
    type: 'Prácticas Pre-Profesionales en Cosmética y Belleza',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '18 a 24 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,500 + Beneficios Belcorp',
    modality: 'hybrid',
    location: 'Sede Central San Isidro (Lima)',
    deadline: '2026-08-25',
    description: 'Gestión de catálogos digitales, análisis de ventas en canales online y desarrollo de promociones para consultoras de belleza.',
    image_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.belcorp.biz/trabaja-con-nosotros/',
    featured: false,
    requirements: ['Estudiantes de Marketing, Administración o Ingeniería Industrial.'],
    benefits: ['Descuentos corporativos en marcas del grupo.', 'Excelente ambiente juvenil de trabajo.']
  },

  // ─── EMPLEOS JUVENILES (Target: 25+) ───
  {
    id: 'empleo-cajero-bancario-2026',
    title: 'Cajero / Promotor de Servicios Bancarios en Ventanilla',
    organization: 'Entidad Financiera Líder en el Perú',
    category: 'job',
    type: 'Empleo en Planilla Completa',
    typeCategory: 'junior',
    ageRange: '18to25',
    ageRangeLabel: '18 a 26 años',
    coverage: 'full',
    coverageLabel: 'Remuneración Básica + Bonos por Cuadre y Productividad',
    modality: 'onsite',
    location: 'Agencias en Lima, Callao, Arequipa, Trujillo, Huancayo',
    deadline: '2026-09-15',
    description: 'Atención al público en ventanilla, recepción y conteo de dinero en efectivo, transferencias y asesoría de productos financieros básicos.',
    image_url: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: true,
    requirements: ['Secundaria completa o estudios técnicos/universitarios en curso o truncos.', 'Deseable curso de cajero bancario o experiencia en atención al cliente.'],
    benefits: ['Ingreso a planilla con todos los beneficios de ley.', 'Línea de carrera bancaria hacia Asesor de Ventas o Subgerente de Agencia.']
  },
  {
    id: 'empleo-soporte-helpdesk-2026',
    title: 'Técnico de Soporte de Mesa de Ayuda (Help Desk Tier 1)',
    organization: 'Empresa de Servicios Tecnológicos & Redes',
    category: 'job',
    type: 'Puesto Fijo Junior de TI',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '18 a 29 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,400 a S/ 1,700 en Planilla',
    modality: 'onsite',
    location: 'Lima (San Isidro / Magdalena)',
    deadline: '2026-08-31',
    description: 'Atención a usuarios corporativos, diagnóstico remoto de hardware y software, configuración de impresoras, correos y redes locales.',
    image_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Egresado técnico o universitario de Computación, Informática o Redes.', 'Conocimiento de sistemas operativos Windows y Office 365.'],
    benefits: ['Capacitaciones continuas en TI.', 'Planilla completa y seguro EsSalud.']
  },
  {
    id: 'empleo-ejecutivo-ventas-junior-2026',
    title: 'Ejecutivo Comercial y de Ventas Corporativas Junior',
    organization: 'Distribuidora Mayorista de Consumo y Tecnología',
    category: 'job',
    type: 'Puesto Comercial en Planilla',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '19 a 28 años',
    coverage: 'full',
    coverageLabel: 'Básico S/ 1,300 + Comisiones Ilimitadas',
    modality: 'onsite',
    location: 'Lima (La Victoria / San Luis)',
    deadline: '2026-09-25',
    description: 'Prospección de nuevos clientes comerciales, gestión de cartera de pedidos, cotizaciones y seguimiento de entregas.',
    image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Excelente facilidad de palabra, persuasión y orientación al cliente.', 'Deseable experiencia en ventas telefónicas o presenciales.'],
    benefits: ['Sueldo básico asegurado más comisiones sin tope.', 'Premios por cumplimiento de metas mensuales.']
  },
  {
    id: 'empleo-asistente-seleccion-rrhh-2026',
    title: 'Asistente Junior de Atracción del Talento & Selección (RR.HH.)',
    organization: 'Consultora de Recursos Humanos & Headhunting',
    category: 'job',
    type: 'Puesto en Planilla General',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '20 a 28 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,500 a S/ 1,800 + Beneficios',
    modality: 'hybrid',
    location: 'Lima (Miraflores)',
    deadline: '2026-08-20',
    description: 'Publicación de ofertas laborales en bolsas de trabajo, filtro curricular, entrevistas por competencias y aplicación de pruebas psicotécnicas.',
    image_url: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Egresado o bachiller de Psicología Organizacional o Administración.', 'Manejo de entrevistas laborales y dinámicas grupales.'],
    benefits: ['Horario flexible y trabajo híbrido.', 'Planilla de ley completa.']
  },
  {
    id: 'empleo-disenador-grafico-junior-2026',
    title: 'Diseñador Gráfico & Productor Visual Junior',
    organization: 'Estudio de Branding & Estrategia Digital',
    category: 'job',
    type: 'Empleo Creativo en Planilla',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '18 a 27 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,600 a S/ 2,000 en Planilla',
    modality: 'hybrid',
    location: 'Lima (Barranco) / Remoto',
    deadline: '2026-09-05',
    description: 'Diseño de identidad visual, piezas gráficas para campañas digitales, banners y material publicitario para marcas de gastronomía y retail.',
    image_url: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: true,
    requirements: ['Egresado de Diseño Gráfico, Publicidad o afines.', 'Dominio de Adobe Illustrator, Photoshop e InDesign. Enviar portafolio.'],
    benefits: ['Equipo de cómputo provisto.', 'Excelente ambiente de innovación creativa.']
  },
  {
    id: 'empleo-asistente-compras-2026',
    title: 'Asistente de Compras y Negociación con Proveedores',
    organization: 'Cadena de Supermercados & Retail',
    category: 'job',
    type: 'Empleo en Planilla de Gran Empresa',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '19 a 28 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,700 + Beneficios Corporativos',
    modality: 'onsite',
    location: 'Lima (Chorrillos)',
    deadline: '2026-08-28',
    description: 'Emisión de órdenes de compra, control de listas de precios, negociación de plazos de entrega y análisis de stocks de reposición.',
    image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Egresado técnico o universitario de Administración, Ing. Industrial o afines.', 'Excel a nivel intermedio (tablas dinámicas y cruce de datos).'],
    benefits: ['Todos los beneficios de ley.', 'Descuentos en compras en las tiendas de la cadena.']
  },
  {
    id: 'empleo-operador-cctv-seguridad-2026',
    title: 'Operador de Centro de Monitoreo de Seguridad (CCTV)',
    organization: 'Empresa de Seguridad y Vigilancia Integral',
    category: 'job',
    type: 'Puesto Fijo en Turnos Rotativos',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '18 a 30 años',
    coverage: 'full',
    coverageLabel: 'Remuneración de Ley + Bonificación Nocturna',
    modality: 'onsite',
    location: 'Lima (Cercado de Lima / San Isidro)',
    deadline: '2026-09-12',
    description: 'Monitoreo de cámaras de seguridad en tiempo real, registro de novedades en bitácora digital y activación de protocolos de emergencia.',
    image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Secundaria completa.', 'Deseable curso básico de operador de cámaras o atención al detalle.'],
    benefits: ['Ingreso directo a planilla desde el primer día con todos los beneficios de ley.', 'Uniformes y capacitaciones cubiertas.']
  },
  {
    id: 'empleo-asistente-mantenimiento-junior-2026',
    title: 'Asistente de Mantenimiento Electromecánico Junior',
    organization: 'Planta de Manufactura Industrial',
    category: 'job',
    type: 'Puesto Técnico en Planilla',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '18 a 28 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,500 a S/ 1,800 + Horas Extras',
    modality: 'onsite',
    location: 'Lima (Zona Industrial Huachipa / San Juan de Lurigancho)',
    deadline: '2026-08-30',
    description: 'Mantenimiento preventivo y correctivo de motores eléctricos, fajas transportadoras, bombas hidráulicas y tableros de control.',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Técnico egresado de Electromecánica, Mecánica de Mantenimiento o afines.', 'Compromiso con las normas de seguridad industrial.'],
    benefits: ['Planilla completa, SCTR y seguro de vida ley.', 'Oportunidad de ascenso a Técnico Especialista.']
  },

  // ─── CONCURSOS & RETOS (Target: 20+) ───
  {
    id: 'concurso-reto-bio-proinnovate-2026',
    title: 'Reto Bio - Proyectos en Biotecnología y Recursos Naturales',
    organization: 'ProInnóvate (Ministerio de la Producción)',
    category: 'competition',
    type: 'Fondo Concursable de I+D+i',
    typeCategory: 'innovation',
    ageRange: 'all',
    ageRangeLabel: 'Investigadores y Emprendedores',
    coverage: 'full',
    coverageLabel: 'Fondos No Reembolsables de hasta S/ 150,000',
    modality: 'virtual',
    location: 'Nacional (Todo el Perú)',
    deadline: '2026-09-30',
    description: 'Concurso para proyectos que agreguen valor a la biodiversidad peruana mediante biotecnología, agricultura regenerativa y biomateriales.',
    image_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.proinnovate.gob.pe/',
    featured: true,
    requirements: ['Equipo multidisciplinario con al menos un especialista técnico o científico.', 'Propuesta alineada a la valorización de recursos biológicos peruanos.'],
    benefits: ['Capital semilla sin devolución ni cesión de acciones.', 'Acceso a laboratorios de investigación certificados.']
  },
  {
    id: 'concurso-hult-prize-peru-2026',
    title: 'Hult Prize Perú - Emprendimiento Universitario con Impacto Global',
    organization: 'Hult Prize Foundation & Universidades Peruanas',
    category: 'competition',
    type: 'Competencia Internacional de Emprendimiento Social',
    typeCategory: 'social',
    ageRange: '18to25',
    ageRangeLabel: 'Estudiantes universitarios',
    coverage: 'full',
    coverageLabel: 'Premios de USD 1,000,000 para el Ganador Mundial',
    modality: 'hybrid',
    location: 'Etapas Locales en PUCP, UNMSM, UNI, UP, UDEP + Final Global',
    deadline: '2026-10-15',
    description: 'El "Premio Nobel de los Estudiantes". Desarrolla un modelo de negocio sostenible que resuelva un desafío social clave de las Naciones Unidas.',
    image_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.hultprize.org/',
    featured: true,
    requirements: ['Equipos de 3 a 4 estudiantes universitarios matriculados en cualquier universidad peruana.'],
    benefits: ['Mentoría con líderes empresariales de nivel internacional.', 'Viaje financiado a las cumbres regionales en el extranjero para los ganadores locales.']
  },
  {
    id: 'concurso-robotica-ieee-peru-2026',
    title: 'Concurso Nacional de Robótica y Automatización IEEE Perú 2026',
    organization: 'IEEE Sección Perú (Robotics and Automation Society)',
    category: 'competition',
    type: 'Competencia Tecnológica de Robótica',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Escolares y Universitarios',
    coverage: 'full',
    coverageLabel: 'Medallas, Trofeos y Premios en Tecnología',
    modality: 'onsite',
    location: 'Campus UNI (Lima)',
    deadline: '2026-10-05',
    description: 'Competencia en categorías de robots velocistas, minisumo, robots autónomos de rescate y drones en pista de obstáculos.',
    image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://ieee.org.pe/',
    featured: false,
    requirements: ['Construir un robot acorde al reglamento oficial de cada categoría.', 'Inscribir al equipo en la plataforma del congreso IEEE.'],
    benefits: ['Certificación internacional IEEE.', 'Acreditación y pase directo para torneos mundiales de robótica en Latinoamérica.']
  },
  {
    id: 'concurso-fondep-innovacion-2026',
    title: 'Concurso Nacional de Proyectos de Innovación Educativa (FONDEP)',
    organization: 'Fondo Nacional de Desarrollo de la Educación Peruana (FONDEP)',
    category: 'competition',
    type: 'Fondo Estatal de Innovación',
    typeCategory: 'education',
    ageRange: 'all',
    ageRangeLabel: 'Docentes y Jóvenes Educadores',
    coverage: 'full',
    coverageLabel: 'Financiamiento Directo de S/ 16,000 por Colegio',
    modality: 'virtual',
    location: 'Nacional',
    deadline: '2026-08-31',
    description: 'Premia y financia iniciativas pedagógicas innovadoras que mejoren los aprendizajes de estudiantes en escuelas públicas de todo el país.',
    image_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.fondep.gob.pe/',
    featured: false,
    requirements: ['Presentar proyecto de innovación educativa formulado por la comunidad escolar.'],
    benefits: ['Subvención directa para compra de materiales didácticos y equipamiento.']
  },
  {
    id: 'concurso-desafio-circular-2026',
    title: 'Desafío Circular Perú - Innovación en Economía Circular & Reciclaje',
    organization: 'Ministerio del Ambiente (MINAM) & Cooperación Alemana (GIZ)',
    category: 'competition',
    type: 'Premio de Sostenibilidad Ambiental',
    typeCategory: 'innovation',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: 'Capital Semilla de S/ 40,000 + Asistencia Técnica',
    modality: 'hybrid',
    location: 'Lima y Regiones',
    deadline: '2026-09-20',
    description: 'Reconoce soluciones innovadoras para la valorización de residuos sólidos, ecodiseño de envases y reutilización de subproductos industriales.',
    image_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.gob.pe/minam',
    featured: false,
    requirements: ['Propuestas con impacto ambiental medible en reducción de residuos.'],
    benefits: ['Acompañamiento por consultores alemanes en economía circular.']
  },

  // ─── VOLUNTARIADOS (Target: 20+) ───
  {
    id: 'voluntariado-bomberos-peru-2026',
    title: 'Cuerpo General de Bomberos Voluntarios del Perú (CGBVP) - Convocatoria de Aspirantes',
    organization: 'Cuerpo General de Bomberos Voluntarios del Perú',
    category: 'volunteer',
    type: 'Servicio de Emergencia y Rescate Nacional',
    typeCategory: 'health',
    ageRange: '18to25',
    ageRangeLabel: '18 a 30 años',
    coverage: 'full',
    coverageLabel: 'Formación Gratuita en la Escuela Básica de Bomberos',
    modality: 'onsite',
    location: 'Compañías de Bomberos a Nivel Nacional (Todas las Regiones)',
    deadline: '2026-10-31',
    description: 'El servicio cívico de mayor honor y entrega del país. Capacítate en combate de incendios, rescate en estructuras colapsadas y atención prehospitalaria.',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.bomberosperu.gob.pe/',
    featured: true,
    requirements: ['Tener vocación de servicio desinteresado y óptimo estado de salud física y mental.', 'No registrar antecedentes policiales ni penales.'],
    benefits: ['Graduación como Bombero Oficial del Perú.', 'Seguro integral médico y beneficios de ley otorgados a bomberos activos.']
  },
  {
    id: 'voluntariado-operacion-sonrisa-2026',
    title: 'Operación Sonrisa Perú - Acompañamiento a Niños en Cirugías Gratuitas',
    organization: 'Operación Sonrisa Perú',
    category: 'volunteer',
    type: 'Voluntariado Médico y Psicosocial',
    typeCategory: 'health',
    ageRange: 'all',
    ageRangeLabel: '17 años a más',
    coverage: 'full',
    coverageLabel: 'Participación Acreditada con Impacto Directo',
    modality: 'onsite',
    location: 'Hospitales de Lima, Piura, Cusco, Iquitos',
    deadline: '2026-09-10',
    description: 'Apoya en las misiones médicas de cirugías gratuitas para niños nacidos con labio leporino y paladar hendido en áreas de triaje, recreación infantil y logística.',
    image_url: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://operacionsonrisa.org.pe/',
    featured: false,
    requirements: ['Sensibilidad humana, paciencia y trato cálido con niños y sus familias.'],
    benefits: ['Constancia oficial de horas de voluntariado de Operación Sonrisa Internacional.']
  },
  {
    id: 'voluntariado-wuf-animales-2026',
    title: 'WUF Perú - Voluntariado en Rescate, Albergues y Adopción Canina',
    organization: 'WUF Perú',
    category: 'volunteer',
    type: 'Voluntariado de Bienestar Animal',
    typeCategory: 'environment',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: 'Participación Libre y Comunitaria',
    modality: 'onsite',
    location: 'Albergues en Pachacámac, Lurín, Cieneguilla y Ferias en Lima',
    deadline: '2026-11-30',
    description: 'Colabora en paseos, socialización, cuidado y campañas de adopción responsable para perritos rescatados en situación de abandono.',
    image_url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.wuf.pe/',
    featured: false,
    requirements: ['Amor por los animales y disposición para actividades recreativas y de cuidado.'],
    benefits: ['Certificado de voluntariado en protección y bienestar animal.']
  },
  {
    id: 'voluntariado-make-a-wish-2026',
    title: 'Make-A-Wish Perú - Voluntariado Hacedores de Sueños',
    organization: 'Make-A-Wish Perú',
    category: 'volunteer',
    type: 'Voluntariado Emocional y Recreativo',
    typeCategory: 'social',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: 'Constancia Internacional',
    modality: 'hybrid',
    location: 'Lima y Principales Ciudades del Perú',
    deadline: '2026-08-31',
    description: 'Transforma la vida de niños diagnosticados con enfermedades críticas ayudando a planificar y hacer realidad su más grande deseo o sueño.',
    image_url: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://makeawish.org.pe/',
    featured: true,
    requirements: ['Creatividad, empatía y compromiso ético estricto.'],
    benefits: ['Capacitación en gestión emocional y voluntariado pediátrico.']
  },
  {
    id: 'voluntariado-caritas-peru-2026',
    title: 'Cáritas del Perú - Brigadas de Emergencia Social & Ayuda Humanitaria',
    organization: 'Cáritas del Perú',
    category: 'volunteer',
    type: 'Voluntariado Social y Humanitario',
    typeCategory: 'social',
    ageRange: 'all',
    ageRangeLabel: '16 a 29 años',
    coverage: 'full',
    coverageLabel: 'Acreditado en el SINAVOL',
    modality: 'onsite',
    location: 'Diócesis de todo el Perú (Costa, Sierra y Selva)',
    deadline: '2026-10-15',
    description: 'Distribución de kits de abrigo en zonas altoandinas afectadas por heladas, canastas de alimentos en emergencias y comedores solidarios.',
    image_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://caritas.org.pe/',
    featured: false,
    requirements: ['Espíritu solidario y disponibilidad para actividades en campo.'],
    benefits: ['Certificación oficial del Ministerio de la Mujer y Poblaciones Vulnerables (MIMP).']
  },
  {
    id: 'voluntariado-aniquem-2026',
    title: 'ANIQUEM - Voluntariado en Rehabilitación y Campañas de Reciclaje',
    organization: 'Asociación de Ayuda al Niño Quemado (ANIQUEM)',
    category: 'volunteer',
    type: 'Voluntariado de Salud y Medio Ambiente',
    typeCategory: 'health',
    ageRange: 'all',
    ageRangeLabel: '17 años a más',
    coverage: 'full',
    coverageLabel: 'Constancia Oficial de Voluntariado',
    modality: 'hybrid',
    location: 'Jesús María (Lima) y Virtual',
    deadline: '2026-09-25',
    description: 'Participa en campañas de prevención de quemaduras, apoyo en talleres recreativos para pacientes y la campaña "Recicla para Ayudar".',
    image_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://aniquem.org/',
    featured: false,
    requirements: ['Ganas de apoyar en actividades lúdicas o de recolección de materiales reciclables.'],
    benefits: ['Constancia de voluntariado acreditada.', 'Impacto directo en terapias de rehabilitación gratuitas.']
  }
];

let added = 0;
for (const item of moreOpportunities) {
  if (!existingIds.has(item.id)) {
    existing.push(item);
    existingIds.add(item.id);
    added++;
  }
}

// Final pass: ensure all BCP links are correct
existing.forEach(item => {
  if (item.external_link && item.external_link.includes('viabcp.com/becas-bcp')) {
    item.external_link = 'https://www.viabcp.com/becasbcp';
  }
});

const fileContent = `export const opportunitiesDetailData = ${JSON.stringify(existing, null, 2)};\n`;
fs.writeFileSync(path.join(rootDir, 'src', 'data', 'opportunitiesDetailData.js'), fileContent, 'utf-8');

console.log(`Added ${added} opportunities in batch 2!`);
console.log(`Final total opportunities: ${existing.length}`);
