import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// Import existing data
import { opportunitiesDetailData as existing } from '../src/data/opportunitiesDetailData.js';

console.log(`Current opportunities count: ${existing.length}`);

// Fix all existing broken BCP links
existing.forEach(item => {
  if (item.external_link && item.external_link.includes('viabcp.com/becas-bcp')) {
    item.external_link = 'https://www.viabcp.com/becasbcp';
  }
});

const existingIds = new Set(existing.map(o => o.id));

const newOpportunities = [
  // ─────────────────────────────────────────────────────────────
  // BECAS ADICIONALES (Target: 25+ Becas)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'beca-continuidad-2026',
    title: 'Beca Continuidad de Estudios 2026',
    organization: 'PRONABEC (Ministerio de Educación)',
    category: 'scholarship',
    type: 'Pregrado en Instituto o Universidad',
    typeCategory: 'undergraduate',
    ageRange: '18to25',
    ageRangeLabel: '18 a 28 años',
    coverage: 'full',
    coverageLabel: '100% Cobertura de Pensiones y Matrícula',
    modality: 'onsite',
    location: 'Nacional (Todo el Perú)',
    deadline: '2026-08-30',
    description: 'Dirigida a estudiantes de educación superior con buen rendimiento académico que hayan sido afectados en su continuidad por situación de vulnerabilidad o emergencias.',
    image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.pronabec.gob.pe/beca-continuidad-de-estudios/',
    featured: true,
    requirements: ['Estar matriculado en universidad o instituto elegible.', 'Pertenecer al tercio superior o equivalente.', 'Acreditar condición de vulnerabilidad socioeconómica (SISFOH).'],
    benefits: ['Matrícula y pensión académica completa.', 'Asignación para movilidad local y útiles de estudio.', 'Acompañamiento tutorial continuo.']
  },
  {
    id: 'beca-hijos-docentes-2026',
    title: 'Beca Hijos de Docentes 2026',
    organization: 'PRONABEC (Ministerio de Educación)',
    category: 'scholarship',
    type: 'Pregrado Universitario / Técnico',
    typeCategory: 'undergraduate',
    ageRange: 'under18',
    ageRangeLabel: 'Hasta 22 años',
    coverage: 'full',
    coverageLabel: '100% Cobertura Integral',
    modality: 'onsite',
    location: 'Nacional (Todo el Perú)',
    deadline: '2026-06-25',
    description: 'Beca exclusiva para hijos de docentes que integran la Carrera Pública Magisterial con destacado rendimiento académico en secundaria.',
    image_url: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.pronabec.gob.pe/beca-hijos-de-docentes/',
    featured: false,
    requirements: ['Hijo de docente de la Carrera Pública Magisterial.', 'Menor de 22 años a la fecha de postulación.', 'Tercio superior en educación secundaria.'],
    benefits: ['Costo de admisión, matrícula y pensiones.', 'Alimentación, movilidad local y laptop.', 'Certificaciones de titulación.']
  },
  {
    id: 'beca-generacion-bicentenario-2026',
    title: 'Beca Generación del Bicentenario - Posgrados en el Extranjero',
    organization: 'PRONABEC (Ministerio de Educación)',
    category: 'scholarship',
    type: 'Maestría y Doctorado Internacional',
    typeCategory: 'postgraduate',
    ageRange: 'over25',
    ageRangeLabel: 'Hasta 35 años (Maestría) / 40 (Doctorado)',
    coverage: 'full',
    coverageLabel: 'Financiamiento 100% en las Mejores Universidades del Mundo',
    modality: 'onsite',
    location: 'EE.UU., Reino Unido, Australia, Europa, Canadá',
    deadline: '2026-07-15',
    description: 'Financiamiento del Estado peruano para cursar maestrías y doctorados en las 400 mejores universidades del ranking mundial (Harvard, Oxford, Cambridge, MIT, Stanford, Melbourne).',
    image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.pronabec.gob.pe/beca-generacion-bicentenario/',
    featured: true,
    requirements: ['Nacionalidad peruana.', 'Grado de bachiller o título profesional con alto rendimiento (décimo o quinto superior).', 'Carta de admisión incondicional a una universidad rankeada en el top 400.'],
    benefits: ['100% de la matrícula y costo académico internacional.', 'Pasajes aéreos internacionales de ida y retorno.', 'Asignación mensual de alojamiento, alimentación y seguro de salud internacional.']
  },
  {
    id: 'beca-mujeres-ciencia-2026',
    title: 'Beca Mujeres en Ciencia - Carreras STEM',
    organization: 'PRONABEC & CONCYTEC',
    category: 'scholarship',
    type: 'Pregrado en Ciencias e Ingenierías',
    typeCategory: 'undergraduate',
    ageRange: 'under18',
    ageRangeLabel: '15 a 22 años',
    coverage: 'full',
    coverageLabel: '100% Cobertura Integral + Mentoría STEM',
    modality: 'onsite',
    location: 'Nacional (Todo el Perú)',
    deadline: '2026-09-15',
    description: 'Fomenta la participación de mujeres jóvenes destacadas en carreras de ciencia, tecnología, ingenierías y matemáticas.',
    image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.pronabec.gob.pe/beca-mujeres-en-ciencia/',
    featured: true,
    requirements: ['Ser mujer de nacionalidad peruana cursando el 5to de secundaria o egresada.', 'Pertenecer al décimo o quinto superior.', 'Postular a una carrera STEM elegible.'],
    benefits: ['Matrícula y cuotas universitarias cubiertas al 100%.', 'Equipo informático de última generación.', 'Mentoría con científicas e ingenieras destacadas.']
  },
  {
    id: 'beca-chevening-peru-2026',
    title: 'Becas Chevening - Maestrías en el Reino Unido',
    organization: 'Gobierno del Reino Unido (FCDO)',
    category: 'scholarship',
    type: 'Maestría de 1 Año en UK',
    typeCategory: 'postgraduate',
    ageRange: 'over25',
    ageRangeLabel: 'Profesionales jóvenes',
    coverage: 'full',
    coverageLabel: 'Financiamiento Total + Vuelos y Visa',
    modality: 'onsite',
    location: 'Reino Unido (Londres, Edimburgo, Manchester, Oxford)',
    deadline: '2026-11-05',
    description: 'El programa de becas internacionales del gobierno británico para formar a los futuros líderes del Perú en las mejores universidades del Reino Unido.',
    image_url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.chevening.org/scholarship/peru/',
    featured: true,
    requirements: ['Grado universitario de bachiller o título.', 'Al menos dos años de experiencia laboral demostrable.', 'Demostrar liderazgo, impacto social e interés de retorno al Perú.'],
    benefits: ['Pensión universitaria completa en cualquier universidad de UK.', 'Estipendio mensual para vivienda y manutención.', 'Vuelos ida y vuelta en clase económica y costo de visa cubierto.']
  },
  {
    id: 'beca-fulbright-peru-2026',
    title: 'Beca Fulbright - Estudios de Posgrado en Estados Unidos',
    organization: 'Comisión Fulbright Perú / Embajada de EE.UU.',
    category: 'scholarship',
    type: 'Maestría y Doctorado en USA',
    typeCategory: 'postgraduate',
    ageRange: 'over25',
    ageRangeLabel: 'Profesionales peruanos',
    coverage: 'full',
    coverageLabel: 'Cobertura Integral en Universidades de EE.UU.',
    modality: 'onsite',
    location: 'Estados Unidos',
    deadline: '2026-05-15',
    description: 'El programa insignia de intercambio académico internacional entre Perú y los Estados Unidos para cursar estudios en prestigiosas universidades norteamericanas.',
    image_url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.fulbright.pe/',
    featured: false,
    requirements: ['Nacionalidad peruana y residencia en el país.', 'Grado universitario con tercio superior.', 'Dominio del idioma inglés (TOEFL o IELTS).'],
    benefits: ['Matrícula universitaria completa.', 'Asignación mensual de sostenimiento.', 'Seguro médico y pasajes internacionales.']
  },
  {
    id: 'beca-santander-estudios-2026',
    title: 'Becas Santander - Excelencia Universitaria & Movilidad',
    organization: 'Banco Santander Perú & Santander Universidades',
    category: 'scholarship',
    type: 'Pregrado y Movilidad Internacional',
    typeCategory: 'undergraduate',
    ageRange: '18to25',
    ageRangeLabel: '18 a 26 años',
    coverage: 'partial',
    coverageLabel: 'Bolsa Económica de S/ 4,000 a USD 2,500',
    modality: 'hybrid',
    location: 'Perú e Iberoamérica',
    deadline: '2026-09-10',
    description: 'Apoyo económico directo y financiamiento de intercambios académicos semestrales para estudiantes universitarios con rendimiento académico sobresaliente.',
    image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.santanderopenacademy.com/',
    featured: false,
    requirements: ['Estar matriculado en una universidad con convenio Santander.', 'Haber completado al menos el 50% de los créditos de la carrera.'],
    benefits: ['Bono económico de manutención.', 'Acceso a cursos certificados internacionales de Santander Open Academy.']
  },
  {
    id: 'beca-alianza-pacifico-2026',
    title: 'Beca de Movilidad Estudiantil Alianza del Pacífico',
    organization: 'Alianza del Pacífico (Chile, Colombia, México, Perú)',
    category: 'scholarship',
    type: 'Intercambio Universitario Semestral',
    typeCategory: 'undergraduate',
    ageRange: '18to25',
    ageRangeLabel: '19 a 27 años',
    coverage: 'full',
    coverageLabel: 'Manutención, Seguro Médico y Pasajes Aéreos',
    modality: 'onsite',
    location: 'Chile, Colombia o México',
    deadline: '2026-06-18',
    description: 'Realiza un semestre académico convalidable en las universidades más prestigiosas de Chile (U. de Chile, UC), Colombia (U. de los Andes, Nacional) o México (UNAM, Tec de Monterrey).',
    image_url: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://becas.alianzapacifico.net/',
    featured: true,
    requirements: ['Estar en la mitad superior de tu carrera universitaria.', 'Contar con carta de aceptación de la universidad de destino en el país miembro.'],
    benefits: ['Asignación mensual de manutención en moneda local.', 'Pasajes aéreos internacionales de ida y vuelta.', 'Seguro de asistencia médica internacional.']
  },
  {
    id: 'beca-cometa-2026',
    title: 'Beca Cometa - Universidades Top de Estados Unidos',
    organization: 'Fundación Romero & Intercorp',
    category: 'scholarship',
    type: 'Pregrado Completo en USA',
    typeCategory: 'undergraduate',
    ageRange: 'under18',
    ageRangeLabel: '15 a 19 años',
    coverage: 'full',
    coverageLabel: '100% Cobertura Integral en Universidades Top',
    modality: 'onsite',
    location: 'Estados Unidos (Ivy League y afines)',
    deadline: '2026-10-20',
    description: 'Prepara y financia la carrera universitaria de escolares peruanos de colegios públicos y privados en las 20 mejores universidades de EE.UU. (Harvard, MIT, Princeton, Columbia, etc.).',
    image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.becacometa.com/',
    featured: true,
    requirements: ['Escolares cursando 4to o 5to de secundaria o recién egresados.', 'Alto potencial académico y extracurricular.', 'Nivel intermedio-avanzado de inglés.'],
    benefits: ['Asesoría integral de admisión a universidades norteamericanas.', 'Financiamiento completo de estudios, vivienda y pasajes.']
  },
  {
    id: 'beca-daaf-alemania-2026',
    title: 'Becas DAAD - Estudios e Investigación en Alemania',
    organization: 'Servicio Alemán de Intercambio Académico (DAAD)',
    category: 'scholarship',
    type: 'Posgrados e Investigación Científica',
    typeCategory: 'postgraduate',
    ageRange: 'over25',
    ageRangeLabel: '22 a 35 años',
    coverage: 'full',
    coverageLabel: 'Subvención Mensual de 934€ a 1,300€ + Seguro',
    modality: 'onsite',
    location: 'Alemania (Múnich, Berlín, Heidelberg, Aquisgrán)',
    deadline: '2026-10-30',
    description: 'Becas completas de maestría y doctorado en áreas de desarrollo sostenible, ingeniería, ciencias naturales y políticas públicas en universidades alemanas.',
    image_url: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.daad.co/es/becas/buscador-de-becas/',
    featured: false,
    requirements: ['Bachiller o titulado con promedio sobresaliente.', 'Inglés fluido (TOEFL/IELTS) o alemán según el programa.', 'Al menos 2 años de experiencia profesional relevante.'],
    benefits: ['Pensión universitaria cubierta.', 'Estipendio mensual de 934 a 1,300 euros para vivir en Alemania.', 'Seguro médico y curso preparatorio del idioma alemán.']
  },
  {
    id: 'beca-bbva-chavos-2026',
    title: 'Beca Universitaria Fundación BBVA Perú',
    organization: 'Fundación BBVA Perú',
    category: 'scholarship',
    type: 'Pregrado Universitario Nacional',
    typeCategory: 'undergraduate',
    ageRange: 'under18',
    ageRangeLabel: '16 a 22 años',
    coverage: 'partial',
    coverageLabel: 'Subvención Económica Anual + Mentoría Financiera',
    modality: 'onsite',
    location: 'Lima, Piura, Trujillo, Arequipa, Cusco, Huancayo',
    deadline: '2026-07-31',
    description: 'Apoyo económico y formativo para jóvenes de escasos recursos que hayan ingresado a universidades aliadas y demuestren liderazgo y vocación de servicio.',
    image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://fundacionbbva.pe/',
    featured: false,
    requirements: ['Haber ingresado a una universidad licenciada.', 'Promedio académico sobresaliente en educación secundaria.', 'Acreditar necesidad económica.'],
    benefits: ['Asignación dineraria mensual de apoyo académico.', 'Mentoría con líderes ejecutivos del BBVA y talleres de habilidades blandas.']
  },
  {
    id: 'beca-mext-japon-2026',
    title: 'Becas Monbukagakusho MEXT - Pregrado y Posgrado en Japón',
    organization: 'Gobierno de Japón (MEXT) / Embajada del Japón en Perú',
    category: 'scholarship',
    type: 'Carreras Universitarias y Posgrado en Japón',
    typeCategory: 'undergraduate',
    ageRange: 'all',
    ageRangeLabel: '17 a 34 años según modalidad',
    coverage: 'full',
    coverageLabel: '100% Cobertura Integral + Año de Japonés',
    modality: 'onsite',
    location: 'Japón (Tokio, Kioto, Osaka, Nagoya)',
    deadline: '2026-06-12',
    description: 'Estudia en universidades japonesas líderes mundiales en tecnología, robótica, arquitectura y medicina con todos los gastos asumidos por el gobierno japonés.',
    image_url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.pe.emb-japan.go.jp/itpr_es/00_000109.html',
    featured: true,
    requirements: ['Nacionalidad peruana.', 'Rendimiento académico destacado.', 'Aprobar exámenes de idioma y matemáticas convocados por la Embajada.'],
    benefits: ['Exención completa de matrícula y mensualidades.', 'Pasaje aéreo de ida y vuelta.', 'Estipendio mensual de aprox. 120,000 yenes.', '1 año completo de aprendizaje intensivo del idioma japonés en Tokio.']
  },

  // ─────────────────────────────────────────────────────────────
  // CURSOS GRATUITOS ADICIONALES (Target: 25+ Cursos)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'curso-google-it-support-2026',
    title: 'Certificado Profesional de Soporte de Tecnologías de la Información de Google',
    organization: 'Google Career Certificates & Coursera',
    category: 'course',
    type: 'Curso Técnico con Certificación Global',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: '100% Gratuito vía Becas Aliadas',
    modality: 'virtual',
    location: 'En Línea / Autogestionado',
    deadline: '2026-11-30',
    description: 'Aprende los conceptos fundamentales de soporte técnico: redes, sistemas operativos, atención al cliente de TI, administración de sistemas y seguridad informática.',
    image_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://grow.google/intl/es/certificates/it-support/',
    featured: true,
    requirements: ['Dispositivo con acceso a internet.', 'Ganas de iniciar carrera en soporte de sistemas sin experiencia previa.'],
    benefits: ['Certificación internacional emitida por Google.', 'Acceso a bolsas de trabajo con empresas internacionales de TI.']
  },
  {
    id: 'curso-google-project-management-2026',
    title: 'Certificado Profesional de Gestión de Proyectos de Google',
    organization: 'Google Career Certificates',
    category: 'course',
    type: 'Especialización en Metodologías Ágiles (Scrum)',
    typeCategory: 'business',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: '100% Gratuito',
    modality: 'virtual',
    location: '100% Online',
    deadline: '2026-10-31',
    description: 'Descubre cómo planificar, ejecutar y gestionar proyectos exitosos utilizando metodologías tradicionales y marcos ágiles (Scrum, Kanban, sprints).',
    image_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://grow.google/intl/es/certificates/project-management/',
    featured: false,
    requirements: ['Disponibilidad de 5 a 10 horas semanales.'],
    benefits: ['Acreditación de más de 100 horas de formación alineada al PMI (Project Management Institute).']
  },
  {
    id: 'curso-microsoft-ai-fundamentals-2026',
    title: 'Microsoft Certified: Azure AI Fundamentals (Inteligencia Artificial)',
    organization: 'Microsoft Learn Perú',
    category: 'course',
    type: 'Certificación Oficial de IA',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: 'Material y Laboratorios 100% Gratuitos',
    modality: 'virtual',
    location: 'Plataforma Microsoft Learn',
    deadline: '2026-12-15',
    description: 'Aprende los principios de la Inteligencia Artificial generativa, visión por computadora, procesamiento de lenguaje natural y machine learning con Azure.',
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://learn.microsoft.com/es-es/credentials/certifications/azure-ai-fundamentals/',
    featured: true,
    requirements: ['Conocimientos básicos de computación.'],
    benefits: ['Vouchers de examen de certificación internacional bonificados.', 'Laboratorios prácticos en la nube sin costo.']
  },
  {
    id: 'curso-ibm-skillsbuild-ia-2026',
    title: 'Fundamentos de Inteligencia Artificial & Prompt Engineering',
    organization: 'IBM SkillsBuild',
    category: 'course',
    type: 'Curso con Insignia Digital IBM',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: '16 años a más',
    coverage: 'full',
    coverageLabel: '100% Libre y Certificado por IBM',
    modality: 'virtual',
    location: 'Plataforma IBM SkillsBuild',
    deadline: '2026-11-20',
    description: 'Comprende el funcionamiento de los modelos de lenguaje (LLMs), ingeniería de prompts, redes neuronales y ética en la inteligencia artificial con casos reales de IBM watsonx.',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://skillsbuild.org/es/',
    featured: true,
    requirements: ['Interés en tecnología e inteligencia artificial.'],
    benefits: ['Credly Digital Badge oficial de IBM verificable en LinkedIn.', 'Ruta directa a especializaciones avanzadas de computación cuántica.']
  },
  {
    id: 'curso-santander-excel-bi-2026',
    title: 'Excel Avanzado & Power BI para la Toma de Decisiones',
    organization: 'Santander Open Academy & Universidad Politécnica de Valencia',
    category: 'course',
    type: 'Especialización en Business Analytics',
    typeCategory: 'business',
    ageRange: 'all',
    ageRangeLabel: 'Jóvenes y Estudiantes',
    coverage: 'full',
    coverageLabel: '100% Beca Gratuita',
    modality: 'virtual',
    location: 'Online Asincrónico',
    deadline: '2026-08-31',
    description: 'Aprende a transformar grandes bases de datos en tableros dinámicos de control (dashboards) usando fórmulas avanzadas de Excel, Power Query y DAX en Power BI.',
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.santanderopenacademy.com/',
    featured: false,
    requirements: ['Manejo elemental de computadora y hoja de cálculo.'],
    benefits: ['Certificado de aprovechamiento avalado por Santander y la UPV.', 'Plantillas y modelos de negocios descargables.']
  },
  {
    id: 'curso-telefonica-marketing-digital-2026',
    title: 'Especialista en Marketing Digital, SEO & Redes Sociales',
    organization: 'Fundación Telefónica Movistar (Conecta Empleo)',
    category: 'course',
    type: 'Ruta de Empleabilidad Certificada',
    typeCategory: 'business',
    ageRange: 'all',
    ageRangeLabel: 'Jóvenes peruanos',
    coverage: 'full',
    coverageLabel: '100% Gratuito y Certificado',
    modality: 'virtual',
    location: 'En Línea (40 horas académicas)',
    deadline: '2026-10-15',
    description: 'Domina estrategias de posicionamiento web (SEO/SEM), creación de contenido publicitario, analítica web y pauta en Meta Ads y TikTok Ads para negocios y marcas personales.',
    image_url: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://conectaempleo-formacion.fundaciontelefonica.com/peru',
    featured: false,
    requirements: ['Interés en comunicación, diseño o ventas digitales.'],
    benefits: ['Certificado digital con código QR de verificación.', 'Acceso a ferias laborales de Conecta Empleo en Lima y regiones.']
  },
  {
    id: 'curso-harvardx-cs50-2026',
    title: 'CS50: Introducción a las Ciencias de la Computación de Harvard',
    organization: 'Harvard University (HarvardX) & edX',
    category: 'course',
    type: 'Curso Universitario de Prestigio Mundial',
    typeCategory: 'tech',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: 'Contenido y Clases 100% Libres y Gratuitas',
    modality: 'virtual',
    location: 'Plataforma edX',
    deadline: '2026-12-31',
    description: 'El curso de introducción a la informática más aclamado del planeta, dictado por el profesor David J. Malan. Aprende algoritmos, estructuras de datos, C, Python, SQL y JavaScript.',
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.edx.org/course/introduction-computer-science-harvardx-cs50x',
    featured: true,
    requirements: ['Disposición a resolver desafíos de lógica y programación.'],
    benefits: ['Certificado de cumplimiento gratuito emitido por el equipo de CS50 de Harvard.', 'Comunidad mundial de más de 4 millones de estudiantes.']
  },
  {
    id: 'curso-fundacion-romero-emprendimiento-2026',
    title: 'Plan de Negocios y Finanzas para Emprendedores Jóvenes',
    organization: 'Campus Romero (Fundación Romero)',
    category: 'course',
    type: 'Curso Empresarial Práctico',
    typeCategory: 'business',
    ageRange: 'all',
    ageRangeLabel: '16 a 29 años',
    coverage: 'full',
    coverageLabel: '100% Gratuito con Beca Virtual',
    modality: 'virtual',
    location: 'Campus Virtual Romero',
    deadline: '2026-09-30',
    description: 'Aprende a formular tu idea de negocio, calcular tu punto de equilibrio, definir tu propuesta de valor y acceder a financiamiento para tu emprendimiento en el Perú.',
    image_url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://campusromero.pe/',
    featured: false,
    requirements: ['Tener una idea de negocio o microempresa en marcha.'],
    benefits: ['Certificado digital oficial del Campus Romero.', 'Postulación a premios de capital semilla de la Fundación Romero.']
  },
  {
    id: 'curso-bid-gestion-proyectos-2026',
    title: 'Gestión de Proyectos de Desarrollo Sostenible (PM4R)',
    organization: 'Banco Interamericano de Desarrollo (BID)',
    category: 'course',
    type: 'Curso Internacional de Políticas Públicas',
    typeCategory: 'business',
    ageRange: 'all',
    ageRangeLabel: 'Universitarios y Jóvenes Profesionales',
    coverage: 'full',
    coverageLabel: 'Acceso Gratuito en Modalidad Auditor',
    modality: 'virtual',
    location: 'edX / BID Academy',
    deadline: '2026-11-15',
    description: 'Metodología oficial del BID (Project Management for Results) para planificar y ejecutar proyectos sociales con alto impacto en América Latina y el Caribe.',
    image_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://academy.iadb.org/es',
    featured: false,
    requirements: ['Interés en gestión pública, impacto social y desarrollo comunitario.'],
    benefits: ['Metodologías y plantillas de gestión de proyectos utilizadas por organismos multilaterales.']
  },

  // ─────────────────────────────────────────────────────────────
  // PRÁCTICAS PRE Y PROFESIONALES ADICIONALES (Target: 25+ Prácticas)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'practicas-bbva-talento-2026',
    title: 'Programa Jóvenes Talentos BBVA 2026',
    organization: 'BBVA Perú',
    category: 'internship',
    type: 'Prácticas Pre-Profesionales en Banca y Finanzas',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '19 a 25 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,600 + FOLA + Beneficios BBVA',
    modality: 'hybrid',
    location: 'Sede Central San Isidro (Lima) y Oficinas Regionales',
    deadline: '2026-08-20',
    description: 'Rotación formativa en áreas de riesgos crediticios, banca comercial, finanzas sostenibles y experiencia del cliente en uno de los grupos financieros más grandes del mundo.',
    image_url: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.bbva.com/es/pe/personas/empleo/',
    featured: true,
    requirements: ['Estudiantes de 7mo a 9no ciclo de Economía, Administración, Ingeniería Industrial o afines.', 'Pertenecer como mínimo al quinto superior.'],
    benefits: ['Subvención económica competitiva superior a ley.', 'Seguro médico FOLA al 100% de cobertura.', 'Línea de carrera acelerada al egresar.']
  },
  {
    id: 'practicas-interbank-innovation-2026',
    title: 'Practicante de Canales Digitales & Experiencia de Usuario',
    organization: 'Interbank (Grupo Intercorp)',
    category: 'internship',
    type: 'Prácticas Pre-Profesionales en Producto Digital',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '18 a 24 años',
    coverage: 'full',
    coverageLabel: 'Subvención Económica + Beneficios del Club Intercorp',
    modality: 'hybrid',
    location: 'Torre Interbank (San Borja, Lima)',
    deadline: '2026-07-28',
    description: 'Diseña y optimiza la experiencia de millones de usuarios en la app móvil y canales de autoservicio de Interbank trabajando junto a diseñadores UX y product owners.',
    image_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://interbank.pe/trabaja-con-nosotros',
    featured: false,
    requirements: ['Estudiantes universitarios de Diseño, Comunicación, Marketing o Ingeniería de Sistemas.', 'Manejo de Figma y nociones de metodologías ágiles.'],
    benefits: ['Subvención económica mensual en planilla formativa.', 'Descuentos exclusivos en empresas del grupo Intercorp (Plaza Vea, Cineplanet, Oechsle).']
  },
  {
    id: 'practicas-alicorp-supply-2026',
    title: 'Programa Trainee de Cadena de Suministro & Operaciones',
    organization: 'Alicorp S.A.A.',
    category: 'internship',
    type: 'Prácticas Pre y Profesionales en Consumo Masivo',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '19 a 26 años',
    coverage: 'full',
    coverageLabel: 'Subvención S/ 1,750 + Alimentación al 100%',
    modality: 'onsite',
    location: 'Planta Callao y Centro de Distribución Lurín',
    deadline: '2026-09-10',
    description: 'Aprende en la empresa líder de alimentos y consumo masivo en el Perú. Gestión de almacenes inteligentes, logística de exportación y optimización de manufactura.',
    image_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.alicorp.com.pe/es/personas/trabaja-con-nosotros/',
    featured: true,
    requirements: ['Estudiantes de últimos ciclos o recién egresados de Ingeniería Industrial, Logística o Comercio Exterior.', 'Disponibilidad para realizar prácticas en plantas de Lima/Callao.'],
    benefits: ['Subvención de S/ 1,750.', 'Alimentación cubierta en comedores corporativos.', 'Movilidad de acercamiento a plantas.']
  },
  {
    id: 'practicas-antamina-mineria-2026',
    title: 'Programa de Prácticas Profesionales Jóvenes Líderes Antamina 2026',
    organization: 'Compañía Minera Antamina',
    category: 'internship',
    type: 'Prácticas Profesionales Mineras',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '20 a 28 años',
    coverage: 'full',
    coverageLabel: 'Subvención Competitiva + Alojamiento y Vuelos en Campamento',
    modality: 'onsite',
    location: 'Campamento Yanacancha (Huari, Áncash) / Régimen Atípico',
    deadline: '2026-06-30',
    description: 'Entrenamiento de alto nivel en una de las minas de cobre y zinc más grandes del mundo en áreas de Operaciones Mina, Geología, Mantenimiento y Medio Ambiente.',
    image_url: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.antamina.com/trabaja-con-nosotros/',
    featured: true,
    requirements: ['Egresados o bachilleres de Ingeniería de Minas, Geología, Metalurgia, Mecánica, Civil o Ambiental.', 'Pertenecer al tercio o quinto superior universitario.'],
    benefits: ['Subvención económica muy por encima de la media de mercado.', 'Alojamiento, alimentación completa y vuelos de traslado en campamento de alta montaña.']
  },
  {
    id: 'practicas-sunat-aduanas-2026',
    title: 'Concurso Público de Prácticas Pre-Profesionales SUNAT 2026',
    organization: 'Superintendencia Nacional de Aduanas y de Administración Tributaria (SUNAT)',
    category: 'internship',
    type: 'Modalidad Formativa en Entidad Pública',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '18 a 26 años',
    coverage: 'full',
    coverageLabel: 'Subvención Mensual S/ 1,400 + Seguro FOLA',
    modality: 'hybrid',
    location: 'Sedes SUNAT a Nivel Nacional (Lima, Callao, Paita, Cusco, Arequipa)',
    deadline: '2026-07-25',
    description: 'Participa en los procesos de fiscalización tributaria, gestión de aduanas marítimas y aéreas, y orientación al contribuyente en el principal ente recaudador del país.',
    image_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://unete.sunat.gob.pe/',
    featured: false,
    requirements: ['Estudiantes universitarios cursando los dos últimos años de Derecho, Contabilidad, Economía o Ing. de Sistemas.', 'No haber realizado prácticas pre-profesionales previas en SUNAT.'],
    benefits: ['Subvención de S/ 1,400 mensuales.', 'Seguro privado de salud.', 'Certificado oficial con gran peso en el sector público y privado.']
  },
  {
    id: 'practicas-ey-auditoria-2026',
    title: 'Programa Trainee en Auditoría & Consultoría Financiera EY',
    organization: 'Ernst & Young (EY Perú)',
    category: 'internship',
    type: 'Prácticas Pre y Profesionales en Big Four',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '19 a 25 años',
    coverage: 'full',
    coverageLabel: 'Subvención Económica + Plan de Carrera Internacional',
    modality: 'hybrid',
    location: 'San Isidro (Lima)',
    deadline: '2026-08-30',
    description: 'Inicia tu carrera profesional en una de las cuatro firmas de consultoría y auditoría más prestigiosas del planeta revisando estados financieros de las corporaciones top del país.',
    image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.ey.com/es_pe/careers',
    featured: false,
    requirements: ['Estudiantes desde 7mo ciclo o recién egresados de Contabilidad, Finanzas o Ingeniería Empresarial.', 'Nivel intermedio o avanzado de inglés.'],
    benefits: ['Formación profesional continua en metodologías internacionales EY.', 'Línea de ascenso a Senior y Gerente.', 'Seguro médico integral.']
  },
  {
    id: 'practicas-osinergmin-ce-2026',
    title: 'Curso de Extensión Universitaria & Prácticas OSINERGMIN',
    organization: 'Organismo Supervisor de la Inversión en Energía y Minería (OSINERGMIN)',
    category: 'internship',
    type: 'Especialización y Prácticas Remuneradas',
    typeCategory: 'pre-pro',
    ageRange: '18to25',
    ageRangeLabel: '20 a 27 años',
    coverage: 'full',
    coverageLabel: 'Beca 100% de Especialización + Prácticas Profesionales',
    modality: 'hybrid',
    location: 'Lima y Oficinas Desconcentradas',
    deadline: '2026-10-15',
    description: 'El programa más reconocido del sector energético y minero para formar a los reguladores y supervisores de electricidad, hidrocarburos y minería en el Perú.',
    image_url: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://ceu.osinergmin.gob.pe/',
    featured: true,
    requirements: ['Egresados o graduados de Derecho, Economía o Ingenierías (Eléctrica, Mecánica, Minas, Química, Petróleo).', 'Pertenecer al tercio superior universitario.'],
    benefits: ['Formación becada con docentes internacionales.', 'Acceso a plazas de prácticas profesionales remuneradas con opción de contratación.']
  },

  // ─────────────────────────────────────────────────────────────
  // EMPLEOS JUVENILES ADICIONALES (Target: 25+ Empleos)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'empleo-asistente-administrativo-2026',
    title: 'Asistente Administrativo y de Gestión Documental Junior',
    organization: 'Corporación Logística y Comercial del Perú',
    category: 'job',
    type: 'Puesto Fijo en Planilla',
    typeCategory: 'junior',
    ageRange: '18to25',
    ageRangeLabel: '18 a 28 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,450 a S/ 1,800 + Beneficios de Ley',
    modality: 'onsite',
    location: 'Lima (Miraflores / Surco)',
    deadline: '2026-08-31',
    description: 'Gestión de expedientes, archivo digital, atención a proveedores, emisión de órdenes de compra y soporte directo a la gerencia administrativa.',
    image_url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Egresado técnico o universitario de Administración, Secretariado o afines.', 'Manejo intermedio de Microsoft Office (Word, Excel, Outlook).'],
    benefits: ['Ingreso a planilla con todos los beneficios (gratificación, CTS, vacaciones).', 'Agradable clima laboral y capacitaciones constantes.']
  },
  {
    id: 'empleo-customer-service-bilingual-2026',
    title: 'Customer Service Representative (Bilingüe Inglés/Español)',
    organization: 'Teleperformance Perú',
    category: 'job',
    type: 'Empleo Formal Bilingüe',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: 'S/ 2,100 a S/ 2,800 + Bonos de Desempeño',
    modality: 'hybrid',
    location: 'Lima (Magdalena del Mar) o Modalidad Trabajo Remoto (WAH)',
    deadline: '2026-09-30',
    description: 'Atención y soporte al cliente para usuarios de marcas globales en EE.UU. y Europa. Oportunidad ideal para jóvenes con buen dominio del inglés sin experiencia técnica.',
    image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: true,
    requirements: ['Inglés avanzado fluido (B2 / C1 hablado y escrito).', 'Secundaria completa o estudios superiores en curso.'],
    benefits: ['Planilla completa desde el primer día de capacitación.', 'Bono de productividad y seguro médico privado (EPS cubierto al 70%).']
  },
  {
    id: 'empleo-analista-powerbi-2026',
    title: 'Analista Junior de Datos & Business Intelligence (Power BI / SQL)',
    organization: 'Consultora de Tecnología & Big Data Perú',
    category: 'job',
    type: 'Empleo Junior en Analítica',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '19 a 29 años',
    coverage: 'full',
    coverageLabel: 'Remuneración S/ 2,200 a S/ 2,600 en Planilla',
    modality: 'virtual',
    location: '100% Remoto (Nacional)',
    deadline: '2026-07-20',
    description: 'Construcción y automatización de paneles de control ejecutivos en Power BI, modelado de datos en SQL Server y soporte en proyectos de transformación digital.',
    image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: true,
    requirements: ['Egresado o bachiller de Ing. de Sistemas, Estadística, Ing. Industrial o afines.', 'Dominio práctico de Power BI, Power Query y consultas SQL.'],
    benefits: ['Trabajo 100% remoto desde cualquier región del Perú.', 'Subvención para cursos y certificaciones internacionales en la nube.']
  },
  {
    id: 'empleo-asistente-contable-2026',
    title: 'Asistente Contable Junior (Tributación & Facturación)',
    organization: 'Estudio Contable & Tributario Asociados',
    category: 'job',
    type: 'Puesto Laboral en Planilla Mype / General',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '19 a 27 años',
    coverage: 'full',
    coverageLabel: 'Remuneración acorde al mercado + Planilla',
    modality: 'onsite',
    location: 'Lima (Lince / Jesús María)',
    deadline: '2026-08-15',
    description: 'Registro de compras y ventas, liquidación de impuestos mensuales (PDT 621, Plame), conciliaciones bancarias y elaboración de libros electrónicos (SIRE).',
    image_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Egresado técnico o universitario de Contabilidad.', 'Conocimiento de normativa tributaria SUNAT y sistemas contables (Concar o Siscont).'],
    benefits: ['Todos los beneficios de ley.', 'Línea de carrera hacia Encargado de Cuenta Contable.']
  },
  {
    id: 'empleo-community-manager-2026',
    title: 'Community Manager & Creador de Contenido Multimedia Junior',
    organization: 'Agencia de Marketing & Publicidad Digital',
    category: 'job',
    type: 'Empleo Creativo Junior',
    typeCategory: 'junior',
    ageRange: 'all',
    ageRangeLabel: '18 a 26 años',
    coverage: 'full',
    coverageLabel: 'Sueldo S/ 1,500 a S/ 1,900 + Bonos por Campaña',
    modality: 'hybrid',
    location: 'Lima (Miraflores) y Remoto',
    deadline: '2026-09-10',
    description: 'Creación y edición de reels/TikToks dinámicos, gestión de comunidades en redes sociales, diseño de piezas en Canva/Photoshop y redacción de copys persuasivos.',
    image_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Estudios en Ciencias de la Comunicación, Publicidad o Marketing.', 'Buen manejo de herramientas de edición de video móvil (CapCut, Premiere).'],
    benefits: ['Ambiente joven, creativo y horizontal.', 'Acceso a eventos y activaciones de marcas aliadas.']
  },
  {
    id: 'empleo-asistente-ssoma-2026',
    title: 'Asistente de Seguridad, Salud en el Trabajo y Medio Ambiente (SSOMA)',
    organization: 'Constructora e Inmobiliaria Metropolitana',
    category: 'job',
    type: 'Puesto Fijo en Obra y Oficinas',
    typeCategory: 'junior',
    ageRange: '18to25',
    ageRangeLabel: '20 a 29 años',
    coverage: 'full',
    coverageLabel: 'S/ 1,800 a S/ 2,300 en Planilla Régimen Construcción/General',
    modality: 'onsite',
    location: 'Lima (Proyectos en San Isidro, Surco y Ate)',
    deadline: '2026-08-25',
    description: 'Supervisión del cumplimiento de protocolos de seguridad en obra, charlas diarias de 5 minutos, control de EPPs y elaboración de informes según la Ley 29783.',
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.empleosperu.gob.pe/',
    featured: false,
    requirements: ['Bachiller o egresado de Ingeniería Ambiental, Industrial o afines.', 'Cursos de especialización en Seguridad y Salud en el Trabajo.'],
    benefits: ['Planilla completa, SCTR y seguro de vida ley.', 'Oportunidad de desarrollo en obras de gran envergadura.']
  },

  // ─────────────────────────────────────────────────────────────
  // CONCURSOS & RETOS ADICIONALES (Target: 20+ Concursos)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'concurso-hackathon-datos-2026',
    title: 'Hackathon Nacional de Datos Abiertos & Soluciones Ciudadanas',
    organization: 'Secretaría de Gobierno y Transformación Digital (PCM)',
    category: 'competition',
    type: 'Desafío Tecnológico Cívico',
    typeCategory: 'hackathon',
    ageRange: 'all',
    ageRangeLabel: 'Jóvenes desarrolladores e innovadores',
    coverage: 'full',
    coverageLabel: 'Premios de S/ 20,000 en Efectivo + Incubación',
    modality: 'hybrid',
    location: 'Lima y Virtual para Todo el Perú',
    deadline: '2026-09-18',
    description: 'Desarrolla prototipos funcionales de software y aplicaciones móviles utilizando datos abiertos del Estado para mejorar la salud, transporte y transparencia pública.',
    image_url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.gob.pe/pcm',
    featured: true,
    requirements: ['Equipos de 3 a 5 personas (desarrolladores, diseñadores, analistas).', 'Solución de código abierto documentada en GitHub.'],
    benefits: ['Premios en efectivo para los 3 primeros puestos.', 'Asesoría de especialistas del Estado para implementación piloto.']
  },
  {
    id: 'concurso-premio-nacional-juventud-2026',
    title: 'Premio Nacional de la Juventud "Yenuri Choki" 2026',
    organization: 'Secretaría Nacional de la Juventud (SENAJU / Minedu)',
    category: 'competition',
    type: 'Premio Estatal al Liderazgo Juvenil',
    typeCategory: 'social',
    ageRange: '18to25',
    ageRangeLabel: '15 a 29 años',
    coverage: 'full',
    coverageLabel: 'Reconocimiento Oficial + Incentivo Económico de S/ 15,450 (3 UIT)',
    modality: 'virtual',
    location: 'Nacional (Todo el Perú)',
    deadline: '2026-08-30',
    description: 'Reconoce la labor meritoria de jóvenes y organizaciones juveniles en categorías de Comunicación Social, Ciencia y Tecnología, Ambiente y Derechos Humanos.',
    image_url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://juventud.gob.pe/premio-nacional-de-la-juventud/',
    featured: true,
    requirements: ['Jóvenes de 15 a 29 años o agrupaciones juveniles registradas en el RENOJ.', 'Evidencias documentadas de impacto social positivo.'],
    benefits: ['Premio económico de 3 Unidades Impositivas Tributarias (UIT).', 'Trofeo, diploma y visibilidad en medios nacionales.']
  },
  {
    id: 'concurso-desafio-kunan-2026',
    title: 'Desafío Kunan - Emprendimientos Sociales & Ambientales',
    organization: 'KUNAN & Movimiento de Innovación Social Perú',
    category: 'competition',
    type: 'Premio al Emprendimiento Social',
    typeCategory: 'innovation',
    ageRange: 'all',
    ageRangeLabel: '18 años a más',
    coverage: 'full',
    coverageLabel: 'Más de S/ 100,000 en Fondos No Reembolsables',
    modality: 'hybrid',
    location: 'Nacional (Todo el Perú)',
    deadline: '2026-09-05',
    description: 'El premio al emprendimiento social más importante del Perú. Impulsa negocios innovadores que resuelvan problemas de pobreza, educación o conservación ambiental.',
    image_url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://kunan.com.pe/',
    featured: false,
    requirements: ['Empresa social formal o asociación con modelo de negocio autosostenible.', 'Operaciones comprobables en el territorio peruano.'],
    benefits: ['Capital no reembolsable en diferentes categorías patrocinadas.', 'Acompañamiento estratégico por líderes empresariales peruanos.']
  },
  {
    id: 'concurso-invenciones-indecopi-2026',
    title: 'Concurso Nacional de Invenciones y Diseños Industriales 2026',
    organization: 'INDECOPI (Dirección de Invenciones y Nuevas Tecnologías)',
    category: 'competition',
    type: 'Concurso de Patentes e Innovación Tecnológica',
    typeCategory: 'innovation',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: 'Financiamiento del Registro de Patente + Trofeo Oficial',
    modality: 'virtual',
    location: 'Nacional',
    deadline: '2026-08-10',
    description: 'Presenta tu invento, dispositivo o modelo de utilidad. INDECOPI premia a los inventores peruanos y financia los costos del trámite de concesión de patente.',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.patenta.pe/',
    featured: false,
    requirements: ['Ser creador o titular de una invención original no patentada previamente.', 'Presentar memoria descriptiva y planos técnicos.'],
    benefits: ['Exención del pago de tasas de solicitud de patente.', 'Exhibición ante inversionistas y delegación para la Feria de Inventos de Ginebra (Suiza).']
  },

  // ─────────────────────────────────────────────────────────────
  // VOLUNTARIADO SOCIAL ADICIONAL (Target: 20+ Voluntariados)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'voluntariado-techo-peru-2026',
    title: 'TECHO Perú - Construcción de Viviendas de Emergencia & Comunidad',
    organization: 'TECHO Perú',
    category: 'volunteer',
    type: 'Voluntariado Comunitario y Social',
    typeCategory: 'social',
    ageRange: 'all',
    ageRangeLabel: '16 años a más',
    coverage: 'full',
    coverageLabel: 'Participación Abierta con Acreditación',
    modality: 'onsite',
    location: 'Lima (San Juan de Lurigancho, Ventanilla, Villa El Salvador) y Trujillo',
    deadline: '2026-10-30',
    description: 'Únete a miles de jóvenes voluntarios para construir viviendas de emergencia y proyectos comunitarios junto a familias de asentamientos humanos en situación de pobreza.',
    image_url: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://peru.techo.org/',
    featured: true,
    requirements: ['Compromiso con el trabajo en equipo y empatía social.', 'Disponibilidad para jornadas de fin de semana.'],
    benefits: ['Constancia de horas de voluntariado acreditadas.', 'Experiencia formativa directa de trabajo comunitario.']
  },
  {
    id: 'voluntariado-ensena-peru-2026',
    title: 'Enseña Perú - Voluntariado Virtual y Presencial de Tutoría Escolar',
    organization: 'Enseña Perú',
    category: 'volunteer',
    type: 'Voluntariado Educativo',
    typeCategory: 'education',
    ageRange: 'all',
    ageRangeLabel: '17 años a más',
    coverage: 'full',
    coverageLabel: 'Certificación Oficial de Impacto Educativo',
    modality: 'hybrid',
    location: 'Nacional (Opción Virtual o en Colegios Aliados)',
    deadline: '2026-09-15',
    description: 'Brinda refuerzo académico en lectura y matemáticas a niños y adolescentes de escuelas rurales y periurbanas del Perú para cerrar brechas de aprendizaje.',
    image_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://ensenaperu.org/',
    featured: true,
    requirements: ['Dedicación de 2 a 4 horas semanales.', 'Paciencia y vocación pedagógica.'],
    benefits: ['Capacitación pedagógica previa certificada.', 'Constancia oficial de voluntariado de alto impacto.']
  },
  {
    id: 'voluntariado-banco-alimentos-2026',
    title: 'Banco de Alimentos Perú - Voluntariado contra el Hambre',
    organization: 'Banco de Alimentos Perú',
    category: 'volunteer',
    type: 'Voluntariado Logístico y Humanitario',
    typeCategory: 'social',
    ageRange: 'all',
    ageRangeLabel: '16 a 29 años',
    coverage: 'full',
    coverageLabel: 'Acreditación Oficial SINAVOL',
    modality: 'onsite',
    location: 'Centro de Operaciones Callao / Almacenes Lima',
    deadline: '2026-11-20',
    description: 'Ayuda en la selección, clasificación y entrega de toneladas de alimentos aptos para consumo rescatados de supermercados hacia comedores populares y ollas comunes.',
    image_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://bancodealimentosperu.org/',
    featured: false,
    requirements: ['Ganas de realizar trabajo dinámico en equipo.'],
    benefits: ['Certificación oficial de voluntariado.', 'Impacto medible en la nutrición de miles de familias.']
  },
  {
    id: 'voluntariado-hazla-playa-2026',
    title: 'Hazla por tu Playa - Voluntariado Ambiental & Limpieza de Costas',
    organization: 'L.O.O.P. & Conservamos por Naturaleza (SPDA)',
    category: 'volunteer',
    type: 'Voluntariado Ecológico y Marino',
    typeCategory: 'environment',
    ageRange: 'all',
    ageRangeLabel: 'Todas las edades',
    coverage: 'full',
    coverageLabel: 'Participación Libre y Comunitaria',
    modality: 'onsite',
    location: 'Playas de Lima, Callao, Paracas, Piura, Tumbes, Moquegua',
    deadline: '2026-08-31',
    description: 'La campaña ciudadana de limpieza costera más grande del Perú. Remueve plásticos de un solo uso y genera conciencia sobre la protección del mar peruano.',
    image_url: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://www.conservamospornaturaleza.org/',
    featured: false,
    requirements: ['Interés activo en el cuidado del medio ambiente.'],
    benefits: ['Guantes y kits de limpieza provistos.', 'Certificado digital de voluntario ambiental.']
  }
];

// Add unique new opportunities
let addedCount = 0;
for (const item of newOpportunities) {
  if (!existingIds.has(item.id)) {
    existing.push(item);
    existingIds.add(item.id);
    addedCount++;
  }
}

const fileContent = `export const opportunitiesDetailData = ${JSON.stringify(existing, null, 2)};\n`;
fs.writeFileSync(path.join(rootDir, 'src', 'data', 'opportunitiesDetailData.js'), fileContent, 'utf-8');

console.log(`Successfully added ${addedCount} new opportunities!`);
console.log(`New total opportunities count: ${existing.length}`);
